// ⭐⭐⭐ THE ALBUM'S HANDWRITING – **GENERATED FROM `docs/specs/album-corpus-2026-09.md`, NEVER
// RETYPED.** 33 occasions × 4 voices × 3 registers = 396 strings, plus the arc's 16 across
// 8 cells: **412 authored strings in total.**
//
// ⭐⭐ THE THREE REGISTERS ARE THREE DIFFERENT THINGS A PARENT DOES ON A PAGE, and his 19.09
// confirmation («всё верно») is what fixes them: the **note** speaks TO her («First day on court. You
// were so excited»), the **caption** speaks ABOUT her («She asked if she could try»), and the **line**
// is the parent thinking aloud («Some journeys start with a simple "Can I?"»). Those three strings are
// HIS OWN, off the mockups, and they are `first-court`'s `sunny` column, character for character.
//
// ⭐⭐ AND THE FOG LAW IS LIFTED HERE – the album spec's §2.8, his ruling 19.09. Temperament reached
// the facts and no surface until this screen (`tests/spirit.test.ts` pins that); the album is the
// exception, because at the end there is nothing left to hide. The parent is the SAME MAN in all four
// voice columns; what differs is the daughter he is describing and therefore what there was to notice.
//
// ⚠⚠ DO NOT EDIT THIS FILE BY HAND. It is written by `tools/album-corpus-emit.ts` and pinned, string
// for string, against the document by `tests/album-corpus-roundtrip.test.ts`. A hand-edit here goes
// red; so does a document edit that was never re-emitted. To change a line, change the DOCUMENT – the
// owner's copy lives there (invariant 4) – then re-run the emitter with `--write`.
//
// ⚠ IT IS ORDINARY COMMITTED SOURCE AND NOT A BUILD STEP. Nothing in `npm run check`, `npm run build`
// or the dev server generates it; the emitter is a one-off, as round 44 ruled for its sibling.
//
// ⭐ WHY GENERATION RATHER THAN TRANSCRIPTION: 412 authored strings. An agent retyping them produces
// typos that no test can catch, because a test written by the same agent compares against what was
// typed. The document is the source of truth; this file is its projection.
//
// ⚠⚠ EVERY STRING HERE IS A **DRAFT** UNTIL HE HAS READ IT. The document says so at its head and
// invariant 4 is the reason: a label, a caption or a sentence on screen is his.
//
// size-budget: generated corpus. Hundreds of lines of authored strings with ONE reason to change, and
// the reason is the document. `scripts/context-audit.mjs`' line trigger is aimed at a source file
// growing past the point where a reader can hold it; this file is not read, it is diffed against
// `tests/album-corpus-roundtrip.test.ts`, and splitting it would buy nothing but two files to
// re-emit. The waiver is acknowledged rather than silent.

import type { Temperament } from '../spirit'

/** The album's chapters. ⚠ `jun` is not among them: spec §3 and §4b – the band under 11 is
 *  unreachable (the world starts at thirteen) and carried 0 milestones on all nine measured careers,
 *  so chapter 1 is the prologue instead. */
export type AlbumBand = 'prologue' | 'young' | 'teen' | 'adult' | 'lateCareer'

/** The family the selector draws an occasion from – the nine `MilestoneType`s plus `prologue`
 *  (the trace persisted at handover), `asset` (`world.assets` and its `boughtWeek`), `rare` (his
 *  super-rare three) and `closing` (the three written frames). */
export type AlbumOccasionKind = 'prologue' | 'title' | 'final' | 'prize' | 'international' | 'injury' | 'season-rank' | 'break-even' | 'school' | 'wedding' | 'asset' | 'rare' | 'closing'

/** ⭐ ONE OCCASION IN ONE VOICE: the three registers, finished. **No placeholders and no
 *  interpolation** – her name is the player's, so the note says «you» and the caption says «she», and
 *  neither ever needs one. The sheet renders the date and her age above the note out of the frame's
 *  own week; no string here writes either, because a corpus cannot know them. */
export interface AlbumHand {
  /** to her, second person – the pasted, torn-edged note */
  note: string
  /** about her, third person – the polaroid's bottom lip */
  caption: string
  /** to nobody – the parent thinking, loose in the margin */
  line: string
}

export interface AlbumOccasion {
  id: string
  kind: AlbumOccasionKind
  bands: readonly AlbumBand[]
  /** `null` where the kind alone is the occasion; otherwise the named condition, resolved engine-side. */
  gate: string | null
  voices: Record<Temperament, AlbumHand>
}

/** ⭐ THE ARC – «сначала она была такой-то, а потом стала такой-то» (his addition, 19.09). The voice
 *  key is what she was BORN (`temperament`, drawn at birth and never changed); the direction is where
 *  `wallsLean` went. ⚠ There is no third direction: spec §4b measured the lean moving on 1 career of
 *  9, and the ruling is that the other eight take the ordinary closing sheet rather than being told
 *  they stayed themselves. ⚠ Two registers, not three – the arc's sentence needs both points in it and
 *  a caption cannot hold two points. */
export type AlbumArcDirection = 'open' | 'reserved'

export interface AlbumArcHand {
  note: string
  line: string
}

export const ALBUM_CORPUS: readonly AlbumOccasion[] = [
  // A1 · first-court
  {
    id: 'first-court',
    kind: 'prologue',
    bands: ['prologue'],
    gate: 'first-pick-on-court',
    voices: {
      sunny: {
        note: 'First day on court. You were so excited.',
        caption: 'She asked if she could try.',
        line: 'Some journeys start with a simple "Can I?"',
      },
      fiery: {
        note: 'First day on court. You wanted to know why the net was in the way.',
        caption: 'She asked whose court it was.',
        line: 'She argued with a net.',
      },
      deep: {
        note: 'You stood at the fence a long time before you went in. Then you didn\'t want to come off.',
        caption: 'She watched the whole hour first.',
        line: 'She watched first. She still does.',
      },
      quiet: {
        note: 'First day on court. You didn\'t say anything about it until we were in the car.',
        caption: 'She carried the racquet all the way home.',
        line: 'She took it home with her.',
      },
    },
  },
  // A2 · first-tournament
  {
    id: 'first-tournament',
    kind: 'prologue',
    bands: ['prologue'],
    gate: 'first-open-played',
    voices: {
      sunny: {
        note: 'Your first tournament. You told everybody in the queue that it was your first tournament.',
        caption: 'She made friends in the queue.',
        line: 'A whole weekend, and she never sat down.',
      },
      fiery: {
        note: 'Your first tournament, and you wanted to know who decides the order of play.',
        caption: 'She read the draw sheet twice.',
        line: 'Somebody had to explain the draw.',
      },
      deep: {
        note: 'You didn\'t eat breakfast and you didn\'t say why until the drive home. Your first tournament.',
        caption: 'She was quiet all morning.',
        line: 'She held it in until the car.',
      },
      quiet: {
        note: 'Your first tournament. You put your shoes by the door the night before.',
        caption: 'Shoes by the door the night before.',
        line: 'She was ready before we were.',
      },
    },
  },
  // A3 · first-win
  {
    id: 'first-win',
    kind: 'prologue',
    bands: ['prologue'],
    gate: 'first-open-with-a-win',
    voices: {
      sunny: {
        note: 'You won one. You told me about the point, not the score.',
        caption: 'She wanted to tell somebody.',
        line: 'She led with the point.',
      },
      fiery: {
        note: 'You won one, and you were furious about the game you dropped.',
        caption: 'She was still cross about one game.',
        line: 'One game. One.',
      },
      deep: {
        note: 'You won one. You said one sentence about it and then wanted to go home.',
        caption: 'She said it once, quietly.',
        line: 'She keeps the good ones somewhere I can\'t see.',
      },
      quiet: {
        note: 'You won one. You asked what time we were leaving.',
        caption: 'She asked about the drive home.',
        line: 'She never once said the word.',
      },
    },
  },
  // A4 · first-cup
  {
    id: 'first-cup',
    kind: 'prologue',
    bands: ['prologue'],
    gate: 'first-open-won-outright',
    voices: {
      sunny: {
        note: 'You won the whole thing. You carried it to the car with both hands.',
        caption: 'Both hands, all the way to the car.',
        line: 'She wouldn\'t let go of it.',
      },
      fiery: {
        note: 'You won the whole thing and announced it before the handshake had finished.',
        caption: 'She told the car park.',
        line: 'The handshake was still going.',
      },
      deep: {
        note: 'You won the whole thing. You looked at it for a long time before you picked it up.',
        caption: 'She looked at it a long time.',
        line: 'She was checking it was real.',
      },
      quiet: {
        note: 'You won the whole thing. You put it in the boot yourself.',
        caption: 'She carried it herself.',
        line: 'Nobody else was allowed to carry it.',
      },
    },
  },
  // A5 · first-title
  {
    id: 'first-title',
    kind: 'title',
    bands: ['young', 'teen', 'adult'],
    gate: 'first-of-kind',
    voices: {
      sunny: {
        note: 'Your first. You rang before you had left the court and I couldn\'t hear a word of it.',
        caption: 'She rang from the court.',
        line: 'I heard the crowd before I heard her.',
      },
      fiery: {
        note: 'Your first. You said you should have had it a year ago.',
        caption: 'A year late, she said.',
        line: 'Nothing is ever on time for her.',
      },
      deep: {
        note: 'Your first. You called late, and the first thing you said was about the second set.',
        caption: 'She called after midnight.',
        line: 'Late, and exact, as usual.',
      },
      quiet: {
        note: 'Your first. You told me the flight time, and then at the end you told me.',
        caption: 'She mentioned it last.',
        line: 'The flight time came first.',
      },
    },
  },
  // A6 · title-step-up
  {
    id: 'title-step-up',
    kind: 'title',
    bands: ['young', 'teen', 'adult', 'lateCareer'],
    gate: 'tier-above-every-previous-title',
    voices: {
      sunny: {
        note: 'A step up, and you were straight on the phone about the court and the noise and the food.',
        caption: 'A bigger court, and she noticed all of it.',
        line: 'She told me about the food.',
      },
      fiery: {
        note: 'A step up. You said the draw had been harder and you wanted that on the record.',
        caption: 'She wanted the draw noted.',
        line: 'For the record, then.',
      },
      deep: {
        note: 'A step up. You said it was the same game with more people watching, and then you went quiet.',
        caption: 'The same game, she said.',
        line: 'More people watching. Same girl.',
      },
      quiet: {
        note: 'A step up. You sent the scoreline and nothing else.',
        caption: 'Just the scoreline.',
        line: 'She let the number do it.',
      },
    },
  },
  // A7 · title-after-injury
  {
    id: 'title-after-injury',
    kind: 'title',
    bands: ['teen', 'adult', 'lateCareer'],
    gate: 'first-title-after-a-layoff',
    voices: {
      sunny: {
        note: 'The first one back. You said you had forgotten how much of it is just standing about waiting.',
        caption: 'She had forgotten the waiting.',
        line: 'All that standing about.',
      },
      fiery: {
        note: 'The first one back, and you said nobody asks about the months off when you win.',
        caption: 'Nobody asks now, she said.',
        line: 'They only ask when she loses.',
      },
      deep: {
        note: 'You had been afraid of the first serve, you told me, and then you weren\'t. The first one back.',
        caption: 'Afraid of the first serve, then not.',
        line: 'She named the fear once it was over.',
      },
      quiet: {
        note: 'The first one back. You said everything was fine. You said it twice.',
        caption: 'She said it twice.',
        line: 'Twice is how I knew.',
      },
    },
  },
  // A8 · title-last
  {
    id: 'title-last',
    kind: 'title',
    bands: ['adult', 'lateCareer'],
    gate: 'last-title-of-the-career',
    voices: {
      sunny: {
        note: 'Nobody told us it was the last one. You would have made more of it, and so would I.',
        caption: 'Nobody knew it was the last.',
        line: 'We would have made more of it.',
      },
      fiery: {
        note: 'Nobody told us it was the last one. You would have had a great deal to say about that.',
        caption: 'She would have had words about it.',
        line: 'No speech. She would have hated that.',
      },
      deep: {
        note: 'You always knew which ones mattered. I think you knew this one was the last before I did.',
        caption: 'She may have known.',
        line: 'She knew which ones mattered.',
      },
      quiet: {
        note: 'It was the last one and nobody knew. You packed the same as always.',
        caption: 'She packed the same as always.',
        line: 'Same bag, same folding.',
      },
    },
  },
  // A9 · first-final
  {
    id: 'first-final',
    kind: 'final',
    bands: ['young', 'teen', 'adult'],
    gate: 'first-of-kind',
    voices: {
      sunny: {
        note: 'Your first final. You told me who was in the stands and what the walk out was like, and I had to ask for the score.',
        caption: 'I had to ask for the score.',
        line: 'The stands came first.',
      },
      fiery: {
        note: 'Your first final. You wanted to be there again next week and you said so before you had sat down.',
        caption: 'Again next week, she said.',
        line: 'Already booking the next one.',
      },
      deep: {
        note: 'Your first final. You said the walk out was longer than you had expected.',
        caption: 'The walk out was longer than she expected.',
        line: 'She counted the steps out.',
      },
      quiet: {
        note: 'Your first final. You told me about the clock at the side of the court.',
        caption: 'She noticed the clock.',
        line: 'The clock, of all things.',
      },
    },
  },
  // A10 · final-lost
  {
    id: 'final-lost',
    kind: 'final',
    bands: ['young', 'teen', 'adult', 'lateCareer'],
    gate: 'final-with-no-title-that-week',
    voices: {
      sunny: {
        note: 'You lost it and you still wanted to talk. That is not nothing, and I hope you know it.',
        caption: 'She wanted to talk anyway.',
        line: 'She rang. That is the part.',
      },
      fiery: {
        note: 'You lost it and you had already decided why by the time you rang.',
        caption: 'She had the reason ready.',
        line: 'The verdict arrived first.',
      },
      deep: {
        note: 'You lost it, and two days later you told me the one point it had turned on.',
        caption: 'Two days, then one point.',
        line: 'She had been holding that point for two days.',
      },
      quiet: {
        note: 'You lost it. You asked about the garden.',
        caption: 'She asked about the garden.',
        line: 'We talked about the garden.',
      },
    },
  },
  // A11 · season-first
  {
    id: 'season-first',
    kind: 'season-rank',
    bands: ['young', 'teen'],
    gate: 'first-season-closed',
    voices: {
      sunny: {
        note: 'Your first season, closed. You wanted to know whether the number was good and I didn\'t know either.',
        caption: 'Neither of us knew if it was good.',
        line: 'A number with nothing to compare it to.',
      },
      fiery: {
        note: 'Your first season closed on a number you said was wrong and would fix.',
        caption: 'She intends to fix it.',
        line: 'Wrong, apparently.',
      },
      deep: {
        note: 'Your first season, closed. You looked at the number for a while and then put the phone down.',
        caption: 'She sat with the number a while.',
        line: 'She read it more than once.',
      },
      quiet: {
        note: 'You wrote the number on the calendar in pencil. That was your first season, closed.',
        caption: 'On the calendar, in pencil.',
        line: 'In pencil, so it could move.',
      },
    },
  },
  // A12 · season-best
  {
    id: 'season-best',
    kind: 'season-rank',
    bands: ['young', 'teen', 'adult', 'lateCareer'],
    gate: 'rank-better-than-every-previous-close',
    voices: {
      sunny: {
        note: 'The best year so far. You listed every week of it and then said you were tired, which was the true part.',
        caption: 'Tired, and pleased, in that order.',
        line: 'The tired bit was the true bit.',
      },
      fiery: {
        note: 'The best year so far, and you spent the whole call on the two weeks that went wrong.',
        caption: 'She only talked about the bad weeks.',
        line: 'Two bad weeks, and that was the call.',
      },
      deep: {
        note: 'The best year so far. You said it had felt like one long week, and I think that was the whole report.',
        caption: 'One long week, she called it.',
        line: 'One long week. That was the report.',
      },
      quiet: {
        note: 'The best year so far. You asked whether we were coming at Christmas.',
        caption: 'She asked about Christmas.',
        line: 'Christmas mattered more.',
      },
    },
  },
  // A33 · season-recovery
  {
    id: 'season-recovery',
    kind: 'season-rank',
    bands: ['teen', 'adult', 'lateCareer'],
    gate: 'rank-better-than-the-previous-close-but-not-a-best',
    voices: {
      sunny: {
        note: 'You came back up the table this year and you talked about the two weeks in the middle where it turned, not about the end of it.',
        caption: 'She talked about the middle of the year.',
        line: 'The turn was in the middle somewhere.',
      },
      fiery: {
        note: 'Better than last year, and you said that was the least it could have been. You were pleased anyway and would not say so.',
        caption: 'The least it could have been, she said.',
        line: 'Pleased, and not admitting it.',
      },
      deep: {
        note: 'You waited until the year was finished before you would call it a climb back, and then you said it in one sentence.',
        caption: 'One sentence, once the year was finished.',
        line: 'She waited for the year to end first.',
      },
      quiet: {
        note: 'A year that went back up. You did not mention it at all, and next season\'s schedule arrived in the same week.',
        caption: 'Nothing said. A new schedule.',
        line: 'Straight back to the planning.',
      },
    },
  },
  // A13 · season-held
  {
    id: 'season-held',
    kind: 'season-rank',
    bands: ['teen', 'adult', 'lateCareer'],
    gate: 'rank-inside-a-narrow-band-of-the-previous-close',
    voices: {
      sunny: {
        note: 'A year of holding on. You said the middle of it had blurred and I know exactly what you mean.',
        caption: 'The middle of it blurred.',
        line: 'A year she can\'t quite remember.',
      },
      fiery: {
        note: 'A year of holding on. You wanted it to be a jump, it wasn\'t, and you said so all winter.',
        caption: 'She wanted a jump.',
        line: 'Holding on was not the plan.',
      },
      deep: {
        note: 'A year of holding on. You said staying still takes more than it looks like it does.',
        caption: 'Staying still costs, she said.',
        line: 'She is right about that.',
      },
      quiet: {
        note: 'A year of holding on. You sent next season\'s schedule two days later.',
        caption: 'Next season\'s schedule, two days later.',
        line: 'Straight on to the next one.',
      },
    },
  },
  // A14 · season-down
  {
    id: 'season-down',
    kind: 'season-rank',
    bands: ['adult', 'lateCareer'],
    gate: 'rank-worse-than-the-previous-close',
    voices: {
      sunny: {
        note: 'A year that went the wrong way. You said so out loud, which is more than most people manage.',
        caption: 'She said it out loud.',
        line: 'Naming it is most of it.',
      },
      fiery: {
        note: 'The year went the wrong way and you had a reason for every week of it, and you meant every one.',
        caption: 'A reason for every week.',
        line: 'All of them true, probably.',
      },
      deep: {
        note: 'A year that went the wrong way. You waited until January to tell me what you thought had happened.',
        caption: 'She waited until January.',
        line: 'She needed the distance first.',
      },
      quiet: {
        note: 'You told me about the flights and the hotels all year, and never once about the year.',
        caption: 'Flights, hotels, not the year.',
        line: 'Everything except the year.',
      },
    },
  },
  // A15 · injury
  {
    id: 'injury',
    kind: 'injury',
    bands: ['young', 'teen', 'adult', 'lateCareer'],
    gate: null,
    voices: {
      sunny: {
        note: 'The week it stopped. You went straight on to what you could still do, which frightened me more than crying would have.',
        caption: 'Straight on to what she could still do.',
        line: 'I would have preferred the crying.',
      },
      fiery: {
        note: 'The week it stopped. You were angry at the floor, the shoes, the schedule and me, in that order.',
        caption: 'Angry at the floor first.',
        line: 'The shoes got it worst.',
      },
      deep: {
        note: 'The week it stopped. You asked how long, and when I said I didn\'t know, you said nothing for a day.',
        caption: 'She asked how long.',
        line: 'A day of nothing, then a question.',
      },
      quiet: {
        note: 'The week it stopped. You asked for a pen and wrote the dates on the calendar.',
        caption: 'Dates on the calendar, in pen.',
        line: 'In pen this time.',
      },
    },
  },
  // A16 · injury-return
  {
    id: 'injury-return',
    kind: 'injury',
    bands: ['young', 'teen', 'adult', 'lateCareer'],
    gate: 'first-week-back-after-a-layoff',
    voices: {
      sunny: {
        note: 'First week back. You said the ball came at you faster than you had remembered, and you laughed about it.',
        caption: 'The ball came faster than she remembered.',
        line: 'She laughed at it, which helped.',
      },
      fiery: {
        note: 'First week back. You wanted all of it back at once, were told no, and I heard about that.',
        caption: 'All of it back at once, please.',
        line: 'They said no. I heard.',
      },
      deep: {
        note: 'First week back. You said you had been more afraid of this week than of the injury.',
        caption: 'More afraid of this than of that.',
        line: 'She waited to say the true thing.',
      },
      quiet: {
        note: 'First week back. You told me what time the session was, which is how you tell me things.',
        caption: 'She told me the time of the session.',
        line: 'That is how she tells me things.',
      },
    },
  },
  // A17 · first-prize
  {
    id: 'first-prize',
    kind: 'prize',
    bands: ['young', 'teen'],
    gate: 'first-of-kind',
    voices: {
      sunny: {
        note: 'The first time it paid. You wanted to spend it on all of us and we had to talk you out of it.',
        caption: 'She wanted to spend it on us.',
        line: 'We talked her out of it.',
      },
      fiery: {
        note: 'The first time it paid you said it wasn\'t very much, and then you kept saying the number.',
        caption: 'Not very much, she said. Repeatedly.',
        line: 'She said the number a lot.',
      },
      deep: {
        note: 'You said the money made the whole thing real in a way the results hadn\'t. The first time it paid.',
        caption: 'Realer than the results, she said.',
        line: 'Money made it real. Not the winning.',
      },
      quiet: {
        note: 'The first time it paid. You asked what the tax on it was.',
        caption: 'She asked about the tax.',
        line: 'Straight to the tax.',
      },
    },
  },
  // A18 · first-international
  {
    id: 'first-international',
    kind: 'international',
    bands: ['young', 'teen'],
    gate: 'first-of-kind',
    voices: {
      sunny: {
        note: 'Your first one abroad. You sent a photograph of the airport ceiling, of all things.',
        caption: 'A photograph of the airport ceiling.',
        line: 'The ceiling. Not the court.',
      },
      fiery: {
        note: 'You had a full opinion on the country before the bags came off. Your first one abroad.',
        caption: 'An opinion before the bags.',
        line: 'She had decided by baggage reclaim.',
      },
      deep: {
        note: 'Your first one abroad. You said everything sounded different and that you liked it, and that was the message.',
        caption: 'Everything sounded different.',
        line: 'She liked the sound of it.',
      },
      quiet: {
        note: 'Your first one abroad. You sent the arrival time.',
        caption: 'Just the arrival time.',
        line: 'Landed. That was the message.',
      },
    },
  },
  // A19 · break-even
  {
    id: 'break-even',
    kind: 'break-even',
    bands: ['teen', 'adult', 'lateCareer'],
    gate: null,
    voices: {
      sunny: {
        note: 'The week it paid for itself. You said we could stop doing sums at the kitchen table and I said we would see.',
        caption: 'No more sums at the kitchen table.',
        line: 'We would see, I said.',
      },
      fiery: {
        note: 'It paid for itself, and you said you had told us it would, and you had, more than once.',
        caption: 'She had told us. She reminded us.',
        line: 'She had told us. Twice.',
      },
      deep: {
        note: 'The week it paid for itself. You knew what it had cost. You had always known.',
        caption: 'She always knew what it cost.',
        line: 'She had been carrying that quietly.',
      },
      quiet: {
        note: 'You asked, in a roundabout way, whether we were all right now. That was the week it paid for itself.',
        caption: 'She asked, in her way, if we were all right.',
        line: 'It took her a while to ask.',
      },
    },
  },
  // A20 · school-done
  {
    id: 'school-done',
    kind: 'school',
    bands: ['young', 'teen'],
    gate: null,
    voices: {
      sunny: {
        note: 'School finished. You came home and told us everybody else\'s plans before your own.',
        caption: 'Everybody else\'s plans first.',
        line: 'Her own plans came last.',
      },
      fiery: {
        note: 'School finished. You said you had been waiting years for it, and then stood in the hall not leaving.',
        caption: 'She stood in the hall a while.',
        line: 'Years of waiting, and then she waited.',
      },
      deep: {
        note: 'School finished. You said you would miss the mornings, which nobody expected, least of all you.',
        caption: 'She will miss the mornings.',
        line: 'Nobody expected the mornings.',
      },
      quiet: {
        note: 'School finished. You cleared the desk that evening and didn\'t mention it again.',
        caption: 'The desk was cleared that evening.',
        line: 'Cleared, and never mentioned.',
      },
    },
  },
  // A21 · wedding
  {
    id: 'wedding',
    kind: 'wedding',
    bands: ['adult', 'lateCareer'],
    gate: null,
    voices: {
      sunny: {
        note: 'You talked to everybody. You have always talked to everybody, and it was the right day for it.',
        caption: 'She talked to everybody.',
        line: 'The right day for it.',
      },
      fiery: {
        note: 'You cried at the wrong moment and were cross about it for a week afterwards.',
        caption: 'Cross about the crying, later.',
        line: 'The wrong moment, she says.',
      },
      deep: {
        note: 'You said one sentence to me before it started and I have not repeated it to anybody.',
        caption: 'One sentence, before it started.',
        line: 'I am keeping that one.',
      },
      quiet: {
        note: 'You checked the time of everything, and then you let the day happen without running it.',
        caption: 'She let somebody else run it.',
        line: 'She stopped checking the time.',
      },
    },
  },
  // A22 · first-house
  {
    id: 'first-house',
    kind: 'asset',
    bands: ['teen', 'adult'],
    gate: 'first-home-bought',
    voices: {
      sunny: {
        note: 'Your own front door. You rang from the empty hall so that I could hear the echo.',
        caption: 'She rang from the empty hall.',
        line: 'I heard the echo.',
      },
      fiery: {
        note: 'Your own front door. You had already decided what was wrong with the kitchen.',
        caption: 'The kitchen was already wrong.',
        line: 'Wrong kitchen, right house.',
      },
      deep: {
        note: 'Your own front door. You said it was strange that a key could do that.',
        caption: 'Strange, what a key can do.',
        line: 'A key, and a different life.',
      },
      quiet: {
        note: 'Your own front door. You sent one photograph, of the door.',
        caption: 'One photograph. The door.',
        line: 'Just the door.',
      },
    },
  },
  // A23 · brand
  {
    id: 'brand',
    kind: 'asset',
    bands: ['teen', 'adult'],
    gate: 'brand-founded',
    voices: {
      sunny: {
        note: 'Your name on something that isn\'t a draw sheet. You thought it was funny. It was also enormous.',
        caption: 'She thought it was funny.',
        line: 'Funny, and enormous.',
      },
      fiery: {
        note: 'They put your name on it and you had the colour changed, because of course you did.',
        caption: 'She had the colour changed.',
        line: 'They changed the colour.',
      },
      deep: {
        note: 'Your name on something that isn\'t a draw sheet. You said it didn\'t feel like yours yet.',
        caption: 'It didn\'t feel like hers yet.',
        line: 'Not hers yet, she said.',
      },
      quiet: {
        note: 'We found out it existed after you had signed for it. Your name, on a thing.',
        caption: 'We were told after the signing.',
        line: 'Afterwards, as usual.',
      },
    },
  },
  // A24 · academy-land
  {
    id: 'academy-land',
    kind: 'asset',
    bands: ['teen', 'adult', 'lateCareer'],
    gate: 'academy-land-bought',
    voices: {
      sunny: {
        note: 'A field, and you walked us round all of it describing courts that weren\'t there.',
        caption: 'She showed us courts that weren\'t there.',
        line: 'All of it, twice round.',
      },
      fiery: {
        note: 'A field, and you were already annoyed about how long everything was going to take.',
        caption: 'Too slow already.',
        line: 'Nothing moves fast enough.',
      },
      deep: {
        note: 'A field. You stood at one end of it for a while and didn\'t say what you were seeing.',
        caption: 'She stood at one end of it.',
        line: 'She was seeing something.',
      },
      quiet: {
        note: 'A field. You had measured it before you told us about it.',
        caption: 'She had measured it first.',
        line: 'Measured, then mentioned.',
      },
    },
  },
  // A25 · academy-courts
  {
    id: 'academy-courts',
    kind: 'asset',
    bands: ['adult', 'lateCareer'],
    gate: 'academy-courts-built',
    voices: {
      sunny: {
        note: 'The courts went in. You hit on the first one before the lines were dry, you said, and I believe you.',
        caption: 'She hit on the first one straight away.',
        line: 'Before the lines were dry.',
      },
      fiery: {
        note: 'The courts went in. You found a fault with the surface on day one and made them come back.',
        caption: 'They came back and did it again.',
        line: 'She made them come back.',
      },
      deep: {
        note: 'The courts went in. You said the sound was wrong, and then a week later that it was right.',
        caption: 'The sound was wrong, then right.',
        line: 'She was listening to it.',
      },
      quiet: {
        note: 'The courts went in. You sent a photograph with nobody in it.',
        caption: 'A photograph with nobody in it.',
        line: 'Empty courts, on purpose.',
      },
    },
  },
  // A26 · academy-built
  {
    id: 'academy-built',
    kind: 'asset',
    bands: ['adult', 'lateCareer'],
    gate: 'academy-building-finished',
    voices: {
      sunny: {
        note: 'The building is up. You gave us the tour twice and told us who each room was going to be for.',
        caption: 'The tour, twice, room by room.',
        line: 'A room for everything.',
      },
      fiery: {
        note: 'The building is up. You said the sign was too small and had a bigger one made.',
        caption: 'The sign was too small.',
        line: 'A bigger sign, then.',
      },
      deep: {
        note: 'The building is up. You said your name looked too big on the front of it.',
        caption: 'Her name looked too big.',
        line: 'Too big, she said. It isn\'t.',
      },
      quiet: {
        note: 'The building is up. You had already worked out where the children would wait.',
        caption: 'She knew where they would wait.',
        line: 'She thought about the waiting.',
      },
    },
  },
  // A27 · lifetime-sponsor
  {
    id: 'lifetime-sponsor',
    kind: 'rare',
    bands: ['adult', 'lateCareer'],
    gate: 'lifetime-contract-signed',
    voices: {
      sunny: {
        note: 'The one that doesn\'t run out. You said you would finally stop being nervous every winter, and then you were nervous anyway.',
        caption: 'Nervous anyway, every winter.',
        line: 'The worry has a habit.',
      },
      fiery: {
        note: 'They offered you the one that doesn\'t run out. You said it should have come years ago, and signed it the same day.',
        caption: 'Years late, signed the same day.',
        line: 'Late, and signed anyway.',
      },
      deep: {
        note: 'The one that doesn\'t run out. You said it was strange to be planned for that far ahead.',
        caption: 'Strange, being planned for.',
        line: 'Somebody planned that far ahead.',
      },
      quiet: {
        note: 'You read the whole thing before you told anybody. The one that doesn\'t run out.',
        caption: 'She read all of it first.',
        line: 'All of it, before a word.',
      },
    },
  },
  // A28 · top-tier-title
  {
    id: 'top-tier-title',
    kind: 'rare',
    bands: ['teen', 'adult', 'lateCareer'],
    gate: 'title-at-the-highest-step',
    voices: {
      sunny: {
        note: 'The big one. You rang and couldn\'t finish a sentence, and neither could I.',
        caption: 'Neither of us finished a sentence.',
        line: 'No sentences, at either end.',
      },
      fiery: {
        note: 'The big one. You said you had been telling people for years and that nobody had listened.',
        caption: 'She had been saying so for years.',
        line: 'Nobody listened. They do now.',
      },
      deep: {
        note: 'The big one. You said the last game had felt like it belonged to somebody else.',
        caption: 'The last game belonged to somebody else.',
        line: 'She watched herself do it.',
      },
      quiet: {
        note: 'The big one. You asked whether we had seen it. We had seen it.',
        caption: 'She asked whether we had seen it.',
        line: 'We had seen it.',
      },
    },
  },
  // A29 · years-at-the-top
  {
    id: 'years-at-the-top',
    kind: 'rare',
    bands: ['adult', 'lateCareer'],
    gate: 'a-run-of-seasons-inside-the-threshold',
    voices: {
      sunny: {
        note: 'Years of it now. You still ring about the food and the courts and the crowd, exactly as you did the first time.',
        caption: 'The same phone calls as the first year.',
        line: 'She hasn\'t changed the call.',
      },
      fiery: {
        note: 'Years of it now. You said staying there is harder than getting there and dared anybody to argue.',
        caption: 'Harder to stay, she says.',
        line: 'Nobody argued.',
      },
      deep: {
        note: 'Years of it now. You said you had stopped noticing it, and then you noticed that.',
        caption: 'She had stopped noticing.',
        line: 'Then she noticed that.',
      },
      quiet: {
        note: 'Years of it now. You still send the flight times.',
        caption: 'Still the flight times.',
        line: 'Every time. Flight times.',
      },
    },
  },
  // A30 · graduated
  {
    id: 'graduated',
    kind: 'closing',
    bands: ['teen', 'adult'],
    gate: 'college-finished',
    voices: {
      sunny: {
        note: 'You finished it. You said the hat was ridiculous and then wore it all afternoon.',
        caption: 'The hat was ridiculous. She kept it on.',
        line: 'All afternoon in that hat.',
      },
      fiery: {
        note: 'You finished it. You said nobody had believed you could do both, and you were right, and we were among them.',
        caption: 'Nobody believed she would do both.',
        line: 'We were among the doubters.',
      },
      deep: {
        note: 'You finished it. You said the last week of it was the hardest week of the year, and you have had some weeks.',
        caption: 'The hardest week of the year.',
        line: 'And she has had some weeks.',
      },
      quiet: {
        note: 'You finished it. You told us the date, and then the time, and then eventually that you had passed.',
        caption: 'The date, the time, then the news.',
        line: 'The news came third.',
      },
    },
  },
  // A31 · farewell
  {
    id: 'farewell',
    kind: 'closing',
    bands: ['adult', 'lateCareer'],
    gate: 'the-last-match',
    voices: {
      sunny: {
        note: 'The last one. You came off talking about the heat and the food and the long ride back, and not about the tennis at all.',
        caption: 'She talked about everything except the tennis.',
        line: 'She saved that part for later, I think.',
      },
      fiery: {
        note: 'The last one. You had a view on it before the bags were packed, and I got all of it on the phone that night.',
        caption: 'A view on it before the bags were packed.',
        line: 'She always did have the last word.',
      },
      deep: {
        note: 'The last one. You stayed on the court after everybody had gone, and I let you.',
        caption: 'She stayed after everybody had gone.',
        line: 'I let her have the court.',
      },
      quiet: {
        note: 'The last one. You folded everything into the bag the same way you always have.',
        caption: 'The bag, packed the usual way.',
        line: 'Same folding. Last time.',
      },
    },
  },
  // A32 · career-ended
  {
    id: 'career-ended',
    kind: 'closing',
    bands: ['adult', 'lateCareer'],
    gate: 'the-career-ended',
    voices: {
      sunny: {
        note: 'That is the album. You will tell it better than I have written it, and louder.',
        caption: 'She will tell it louder.',
        line: 'Her version is better.',
      },
      fiery: {
        note: 'You will disagree with some of this, and I have left room. That is the album.',
        caption: 'She will disagree with some of it.',
        line: 'I left room for the argument.',
      },
      deep: {
        note: 'That is the album. You will find the one week I have got wrong, and you will be right.',
        caption: 'She will find the week I got wrong.',
        line: 'She will be right, too.',
      },
      quiet: {
        note: 'You will read it all the way through and say very little, and I will know. That is the album.',
        caption: 'She will read it all and say little.',
        line: 'I will know what it meant.',
      },
    },
  },
]

export const ALBUM_ARC: Record<AlbumArcDirection, Record<Temperament, AlbumArcHand>> = {
  // the lean moved towards open
  open: {
    sunny: {
      note: 'You were always easy to talk to. It took me years to learn that easy to talk to and easy to know are not the same thing, and now I know you.',
      line: 'The bright part was never the whole of it.',
    },
    fiery: {
      note: 'You always told us what you thought. Somewhere in here you started telling us what you felt, which is a different thing and took longer.',
      line: 'The verdicts were never the hard part.',
    },
    deep: {
      note: 'You used to take a week to tell me one true sentence. Lately you say it the same day. It is still one sentence and it is still true.',
      line: 'Same sentence. Sooner.',
    },
    quiet: {
      note: 'For years I got the schedule when I asked how you were. This year I got the answer.',
      line: 'She stopped telling me the timetable.',
    },
  },
  // the lean moved towards reserved
  reserved: {
    sunny: {
      note: 'You used to tell me everything in the week it happened. Some of it is yours now, and I have had to learn that this is not a door closing.',
      line: 'Not a door closing. I had to learn that.',
    },
    fiery: {
      note: 'You used to decide before the sentence was finished. Now you take the evening first. I miss the noise a little.',
      line: 'She kept the fire. She learned where to put it.',
    },
    deep: {
      note: 'You were always exact, and always late with it. You are more exact now, and later still, and I have stopped hurrying you.',
      line: 'I stopped hurrying her.',
    },
    quiet: {
      note: 'You have always kept your own counsel. You keep more of it now, and what you do say has got heavier, and I listen harder.',
      line: 'Less said. More in it.',
    },
  },
}
