// L3-7 (10.10) – THE COMMENTARY, THE PREVIEW AND THE BOOTH RIDE THE VIEWER AS COPYREFS BESIDE THE ENGLISH. docs/specs/i18n-2026-10.md §3.2, §8 rows L3-4 / L3-7.
//
// WHAT THE WAVE DID TO `src/viz/commentary.ts` AND `src/viz/preview.ts`: every sentence they compose is now a `Line` – the English they always returned AND the `CopyRef` that translates it, made from ONE
// `cp` template (`src/viz/lines.ts`: the English is the ref rendered under the source locale, so the two cannot drift). The beat carries `leadC` / `textC`, the preview line `c`; clauses join as `{0} {1}`
// (each carried as a nested ref); a counted thing is a sentence per form; the engine-born words (names, round and tier labels, the spelled count words, a set's ordinal) pass as params. No `t()`, no UI import.
//
// WHAT THIS FILE PROVES:
//   §1 the key law – the `cp` keys of the three viz files are exactly the listed ones (a new or reworded sentence is a decision), every one a key of the English catalog, none carrying a context tag;
//   §2 refs render === strings – every beat of the grid (3,293 builds, the occasion ladder x the coach, private-life and lineage packets), every preview line (8,066 builds), and the booth pools' cells;
//   §3 completeness – which keys the grid reaches, and the named few it cannot;
//   §4 the pick keys are immovable – the rotor's families, the hash, and the absence of any draw;
//   §5 the exports a test reads still read as strings (`boothLineageLines` cells return a Line whose `text` is the sentence).
// The twin against the pre-wave tree (3,293 + 8,066 digests, five careers x 300 weeks, a college career) is `tests/i18n-l3-7-twin.test.ts`; the mounted proof is `tests/component/i18n-l3-7-viz-display.test.ts`.
import { describe, expect, it } from 'vitest'
import ts from 'typescript'
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { renderCopyRef, SOURCE_LOCALE, splitContext, type CopyRef } from '../src/shared/i18n'
import { boothLineageLines, buildCommentary } from '../src/viz/commentary'
import { simulateMatch } from '../src/engine/match/engine'
import { annotateMatch } from '../src/engine/match/rally'
import type { MatchPlayer } from '../src/engine/match/types'
import { eachCommentary, previewInputs } from './helpers/l3-7-play'
import { buildPreview } from '../src/viz/preview'
import { VIZ_CLASS_B_KEYS } from './helpers/l3-7-viz-keys'

const ROOT = resolve(__dirname, '..')
const EN = { locale: SOURCE_LOCALE }
const FILES = ['src/viz/commentary.ts', 'src/viz/preview.ts', 'src/viz/lines.ts']
const SRC = (rel: string): string => readFileSync(resolve(ROOT, rel), 'utf8')

/** every `cp` template in a file, as the key `cp` makes of it */
function cpKeys(rel: string): string[] {
  const sf = ts.createSourceFile(rel, SRC(rel), ts.ScriptTarget.Latest, true)
  const out: string[] = []
  const go = (n: ts.Node): void => {
    if (ts.isTaggedTemplateExpression(n) && n.tag.getText() === 'cp') {
      const tpl = n.template
      if (ts.isNoSubstitutionTemplateLiteral(tpl)) out.push(tpl.text)
      else {
        let k = tpl.head.text
        tpl.templateSpans.forEach((s, i) => {
          k += `{${i}}${s.literal.text}`
        })
        out.push(k)
      }
    }
    ts.forEachChild(n, go)
  }
  go(sf)
  return out
}
const SCANNED = [...new Set(FILES.flatMap(cpKeys))].sort()

if (process.env.L37_WRITE_KEYS) {
  const body = SCANNED.map((k) => `  ${JSON.stringify(k)},`).join('\n')
  writeFileSync(
    resolve(ROOT, 'tests/helpers/l3-7-viz-keys.ts'),
    `// GENERATED by tests/i18n-l3-7-viz.test.ts (\`L37_WRITE_KEYS=1 npx vitest run --project unit tests/i18n-l3-7-viz.test.ts\`) and held to the scan by its §1 – the \`cp\` keys of src/viz/commentary.ts, preview.ts and lines.ts.\n// Class (b): assembled by the viewer's builders at render time, never stored, so the frozen v92 table (a table of STORED rows) has no entry for any of them.\nexport const VIZ_CLASS_B_KEYS: readonly string[] = [\n${body}\n]\n`,
  )
}

/** every key a ref names, nested ones included */
function keysOf(ref: CopyRef | undefined, into: Set<string>): void {
  if (!ref) return
  into.add(ref.k)
  for (const p of ref.p ?? []) if (typeof p === 'object' && p !== null) keysOf(p as CopyRef, into)
}

describe('§1 the key law – the viz files\' cp keys are the listed ones, wired, and plain', () => {
  it('the scan equals the list (a new sentence, or a reworded one, is a decision)', () => {
    expect([...VIZ_CLASS_B_KEYS].sort()).toEqual(SCANNED)
  })

  it('every key is a key of the English catalog (the extractor reads them)', () => {
    const catalog = JSON.parse(SRC('src/i18n/catalog.en.json')) as { keys: Record<string, unknown> }
    const missing = SCANNED.filter((k) => !(k in catalog.keys))
    expect(missing).toEqual([])
  })

  it('no key carries a context tag, a brace the formatter would eat, or an edge space (the English renders as written)', () => {
    for (const k of SCANNED) {
      expect(splitContext(k).ctx, k).toBeNull()
      expect(k.includes('\\'), `a backslash in ${k} – the formatter would read it as an escape`).toBe(false)
      expect(k, `edge space in «${k}»`).toBe(k.trim())
      const holes = [...k.matchAll(/\{(\d+)\}/g)].map((m) => Number(m[1]))
      expect(holes, k).toEqual(holes.map((_, i) => i))
    }
  })

  it('the joins are the two generic keys (`{0} {1}` and `{0} {1} {2}`) – a clause chain is never a flattened key', () => {
    expect(SCANNED.filter((k) => /^\{\d+\}( \{\d+\})+$/.test(k))).toEqual(['{0} {1}', '{0} {1} {2}'])
  })
})

describe('§2 refs render === strings – the grid, the preview and the booth pools', () => {
  it('every beat of every build: the lead and the text render to the English the beat carries; the refs are JSON-safe', () => {
    let beats = 0
    const reached = new Set<string>()
    const bad: string[] = []
    eachCommentary((label, list) => {
      for (const b of list) {
        beats++
        if (b.lead === null) {
          if (b.leadC !== undefined) bad.push(`${label} lead is null but leadC is set`)
        } else {
          if (!b.leadC) bad.push(`${label} ${b.kind}: lead without a ref`)
          else if (renderCopyRef(b.leadC, EN) !== b.lead) bad.push(`${label} ${b.kind}: lead «${b.lead}» renders «${renderCopyRef(b.leadC, EN)}»`)
        }
        if (!b.textC) bad.push(`${label} ${b.kind}: text without a ref`)
        else {
          if (renderCopyRef(b.textC, EN) !== b.text) bad.push(`${label} ${b.kind}: «${b.text}» renders «${renderCopyRef(b.textC, EN)}»`)
          if (JSON.stringify(JSON.parse(JSON.stringify(b.textC))) !== JSON.stringify(b.textC)) bad.push(`${label}: ref is not JSON-safe`)
        }
        keysOf(b.leadC, reached)
        keysOf(b.textC, reached)
      }
    })
    expect(beats, 'a non-empty denominator').toBeGreaterThan(50_000)
    expect(bad.slice(0, 8)).toEqual([])
    GRID_REACHED = reached
  })

  it('every preview line of every build: `c` renders to the text', () => {
    let lines = 0
    const bad: string[] = []
    const reached = new Set<string>()
    for (const { label, input } of previewInputs()) {
      for (const l of buildPreview(input)) {
        lines++
        if (!l.c) bad.push(`${label} ${l.key}: no ref`)
        else if (renderCopyRef(l.c, EN) !== l.text) bad.push(`${label} ${l.key}: «${l.text}» renders «${renderCopyRef(l.c, EN)}»`)
        keysOf(l.c, reached)
      }
    }
    expect(lines, 'a non-empty denominator').toBeGreaterThan(40_000)
    expect(bad.slice(0, 8)).toEqual([])
    PREVIEW_REACHED = reached
  })

  it('the booth pools: every cell of the three lineage pools returns a Line whose ref renders to its text, for names with awkward characters too', () => {
    for (const ctx of [{ proTitles: 6, collegeTitles: 0, slams: 1 }, { proTitles: 0, collegeTitles: 1, slams: 0 }, { proTitles: 0, collegeTitles: 0, slams: 0 }]) {
      const pool = boothLineageLines({ side: 0, ...ctx })
      expect(pool.length).toBe(2)
      for (const cell of pool) {
        for (const who of ['Nadia', "O'Brien-Smith", 'Top seed', '{0}', 'Ines {1} Duval']) {
          const l = cell(who)
          expect(renderCopyRef(l.c, EN), who).toBe(l.text)
          expect(l.text, 'the name is a param, byte for byte').toContain(who)
        }
      }
    }
  })
})

let GRID_REACHED = new Set<string>()
let PREVIEW_REACHED = new Set<string>()

describe('§3 completeness – the keys the grid reaches', () => {
  it('every key of the three files is reached by the commentary grid, the preview grid or the lead table – bar the named few', () => {
    const reached = new Set<string>([...GRID_REACHED, ...PREVIEW_REACHED])
    const unreached = SCANNED.filter((k) => !reached.has(k))
    // the keys no seeded match, rung or packet of the grid can say – each with the reason it is still a key:
    //   the 21+ count forms and set ordinals beyond the fifth are digits, not keys; `and a place in the round of {0}` needs a round of 128 or 64 whose label a played match reaches (it is in the grid: opener rows of the big draws)
    expect(unreached, 'keys no row of the grid reached').toEqual(UNREACHED)
  })
})
/** The keys no row of the grid reaches, each with its reason.
 *  · TWELVE ARE UNREACHABLE BY CONSTRUCTION, and the old code had the same twelve branches (`outcomeLine` spelt them through `descriptorOf`): the beat's HERO is the player who won the game or the set,
 *    so the deciding point is hers – her own last ball is an ace or a winner, never a miss («She loses the point with …», seven), and the other player's last ball is a miss or a double fault, never a
 *    winner or an ace («{0} wins the {1} with …», three; «{0} ends it with a winner {1}.» and «{0} shots, and {1} ends it {2}.», the two non-hero winner moulds of `mannerLine`). They are kept so a branch that
 *    cannot be reached today and can tomorrow does not fall back to English; they cost a translator twelve rows, and the editorial doc already spells the hero-loses family (RU-08 §16.3).
 *  · ONE IS REACHABLE AND SIMPLY RARE: an ace into the body at a deciding point (20% of serves go there, and an ace is the clause of a break, a hold or a set in about one beat in sixty) – §3's second test finds it. */
const UNREACHED: string[] = [
  'She loses the point with a double fault.',
  'She loses the point with a long groundstroke.',
  'She loses the point with a long return.',
  'She loses the point with a netted groundstroke.',
  'She loses the point with a netted return.',
  'She loses the point with a wide groundstroke.',
  'She loses the point with a wide return.',
  '{0} ends it with a winner {1}.',
  '{0} shots, and {1} ends it {2}.',
  '{0} wins the {1} with a second-serve ace {2}.',
  '{0} wins the {1} with a winner {2}.',
  '{0} wins the {1} with an ace {2}.',
  'into the body',
].sort()

describe('§3b the rare one is sayable', () => {
  it('an ace into the body at a deciding point: seed l37-body-95 (found by a search of 800 grass matches; one build is the proof)', () => {
    const A: MatchPlayer = { id: 'kid', name: 'Bianca Tran', serve: 78, ret: 55, composure: 42, stamina: 61, groundstrokes: 56 }
    const B: MatchPlayer = { id: 'opp', name: 'Dana Delgado', serve: 60, ret: 57, composure: 55, stamina: 60, groundstrokes: 58 }
    const opts = { surface: 'grass' as const, tour: 'wta' as const, seed: 'l37-body-95' }
    const m = annotateMatch(simulateMatch(A, B, opts), A, B, opts)
    const beat = buildCommentary(m, A.name, B.name, null).find((b) => /ace into the body/.test(b.text))
    expect(beat?.text).toBe('Bianca serves out the first set. She wins the point with an ace into the body.')
    expect(beat?.textC && renderCopyRef(beat.textC, EN)).toBe(beat?.text)
    const keys = new Set<string>()
    keysOf(beat?.textC, keys)
    expect(keys.has('into the body')).toBe(true)
  })
})

describe('§4 the pick keys are immovable – no draw, no new family, the hash and the rotor as they were', () => {
  const src = SRC('src/viz/commentary.ts')
  it('the rotor\'s families are the four it had, and `variant` is the hash it was', () => {
    const families = [...new Set([...src.matchAll(/pick\('([a-z]+)'/g)].map((m) => m[1]))].sort()
    expect(families).toEqual(['break', 'hold', 'level', 'manner'])
    expect(src).toContain('return (Math.imul(pointIndex + 1, 2654435761) >>> 0) % n')
    expect(src).toContain('const ROTOR_MEMORY = 2')
  })

  it('the file draws nothing: no `rngFromSeed`, no `Math.random`, no clock', () => {
    for (const rel of FILES) {
      const code = SRC(rel).replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '')
      expect(code, rel).not.toMatch(/rngFromSeed|Math\.random|new Date|Date\.now/)
    }
  })

  it('the files import no UI layer and call no t(): refs only', () => {
    for (const rel of FILES) {
      const imports = [...SRC(rel).matchAll(/^import [^\n]* from '([^']+)'/gm)].map((m) => m[1]!)
      for (const from of imports) expect(/(^|\/)i18n$/.test(from) && !from.endsWith('shared/i18n'), `${rel} imports the UI i18n layer: ${from}`).toBe(false)
      expect(imports.some((i) => i.endsWith('vue') || i.includes('pinia')), rel).toBe(false)
    }
    expect(SRC('src/viz/commentary.ts')).toMatch(/import \{ cp, type CopyRef \} from '..\/shared\/i18n'/)
    expect(SRC('src/viz/preview.ts')).toMatch(/import \{ cp, type CopyRef \} from '..\/shared\/i18n'/)
  })
})
