// ⭐⭐⭐ THE ONE-OFF THAT WRITES `src/engine/world/albumCorpus.ts`.
//
//     npx vite-node tools/album-corpus-emit.ts            # print to stdout
//     npx vite-node tools/album-corpus-emit.ts --write    # write the module
//
// ⚠⚠ IT IS A ONE-OFF AND NOT A BUILD STEP – round 44's ruling, carried: «its output is committed as
// ordinary source – no build step, no codegen in the pipeline, boring TypeScript intact». Nothing in
// `npm run check`, `npm run build` or the dev server runs this file. What keeps the committed module
// honest is `tests/album-corpus-roundtrip.test.ts`, which re-parses the document on every run and
// compares it to the committed catalogue STRING FOR STRING – so a hand-edit of the generated file
// goes red, and so does a document edit that was never re-emitted.
//
// ⚠ RE-RUNNING IT IS THE ONLY LEGITIMATE WAY TO CHANGE THE 400. When the owner edits a line in
// `docs/specs/album-corpus-2026-09.md`, run this with `--write` and commit the result; do not touch
// the generated module by hand. **The copy is his** (invariant 4) and the document is where it lives.

import { writeFileSync } from 'node:fs'
import {
  readAlbumCorpus,
  albumCounts,
  ALBUM_ARC_DIRECTIONS,
  ALBUM_BANDS,
  ALBUM_KINDS,
  ALBUM_VOICES,
} from './album-corpus-parse'
import type { AlbumCorpus, AlbumRow, AlbumArcRow } from './album-corpus-parse'

const OUT = new URL('../src/engine/world/albumCorpus.ts', import.meta.url)

/** ⚠ SINGLE-QUOTED, AND THE ESCAPES ARE THE ONLY TWO THAT MATTER: the backslash first (or it would
 *  escape the escapes that follow it) and the quote. The handwriting is full of apostrophes –
 *  «didn't», «she'd», «everybody's» – which is precisely why this is emitted and not typed. */
function q(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

function union(values: readonly string[]): string {
  return values.map((v) => `'${v}'`).join(' | ')
}

function emitOccasion(row: AlbumRow): string[] {
  const out: string[] = []
  out.push(`  // ${row.ref} · ${row.id}`)
  out.push('  {')
  out.push(`    id: ${q(row.id)},`)
  out.push(`    kind: ${q(row.kind)},`)
  out.push(`    bands: [${row.bands.map(q).join(', ')}],`)
  out.push(`    gate: ${row.gate === null ? 'null' : q(row.gate)},`)
  out.push('    voices: {')
  for (const voice of ALBUM_VOICES) {
    const hand = row.voices[voice]
    out.push(`      ${voice}: {`)
    out.push(`        note: ${q(hand.note)},`)
    out.push(`        caption: ${q(hand.caption)},`)
    out.push(`        line: ${q(hand.line)},`)
    out.push('      },')
  }
  out.push('    },')
  out.push('  },')
  return out
}

function emitArc(row: AlbumArcRow): string[] {
  const out: string[] = []
  out.push(`  // ${row.gloss}`)
  out.push(`  ${row.direction}: {`)
  for (const voice of ALBUM_VOICES) {
    const hand = row.voices[voice]
    out.push(`    ${voice}: {`)
    out.push(`      note: ${q(hand.note)},`)
    out.push(`      line: ${q(hand.line)},`)
    out.push('    },')
  }
  out.push('  },')
  return out
}

export function emit(corpus: AlbumCorpus = readAlbumCorpus()): string {
  const counts = albumCounts(corpus)
  const authored = counts.notes + counts.captions + counts.lines + counts.arcStrings
  const head = `// ⭐⭐⭐ THE ALBUM'S HANDWRITING – **GENERATED FROM \`docs/specs/album-corpus-2026-09.md\`, NEVER
// RETYPED.** ${counts.occasions} occasions × ${ALBUM_VOICES.length} voices × 3 registers = ${counts.notes + counts.captions + counts.lines} strings, plus the arc's ${counts.arcStrings} across
// ${counts.arcCells} cells: **${authored} authored strings in total.**
//
// ⭐⭐ THE THREE REGISTERS ARE THREE DIFFERENT THINGS A PARENT DOES ON A PAGE, and his 19.09
// confirmation («всё верно») is what fixes them: the **note** speaks TO her («First day on court. You
// were so excited»), the **caption** speaks ABOUT her («She asked if she could try»), and the **line**
// is the parent thinking aloud («Some journeys start with a simple "Can I?"»). Those three strings are
// HIS OWN, off the mockups, and they are \`first-court\`'s \`sunny\` column, character for character.
//
// ⭐⭐ AND THE FOG LAW IS LIFTED HERE – the album spec's §2.8, his ruling 19.09. Temperament reached
// the facts and no surface until this screen (\`tests/spirit.test.ts\` pins that); the album is the
// exception, because at the end there is nothing left to hide. The parent is the SAME MAN in all four
// voice columns; what differs is the daughter he is describing and therefore what there was to notice.
//
// ⚠⚠ DO NOT EDIT THIS FILE BY HAND. It is written by \`tools/album-corpus-emit.ts\` and pinned, string
// for string, against the document by \`tests/album-corpus-roundtrip.test.ts\`. A hand-edit here goes
// red; so does a document edit that was never re-emitted. To change a line, change the DOCUMENT – the
// owner's copy lives there (invariant 4) – then re-run the emitter with \`--write\`.
//
// ⚠ IT IS ORDINARY COMMITTED SOURCE AND NOT A BUILD STEP. Nothing in \`npm run check\`, \`npm run build\`
// or the dev server generates it; the emitter is a one-off, as round 44 ruled for its sibling.
//
// ⭐ WHY GENERATION RATHER THAN TRANSCRIPTION: ${authored} authored strings. An agent retyping them produces
// typos that no test can catch, because a test written by the same agent compares against what was
// typed. The document is the source of truth; this file is its projection.
//
// ⚠⚠ EVERY STRING HERE IS A **DRAFT** UNTIL HE HAS READ IT. The document says so at its head and
// invariant 4 is the reason: a label, a caption or a sentence on screen is his.
//
// size-budget: generated corpus. Hundreds of lines of authored strings with ONE reason to change, and
// the reason is the document. \`scripts/context-audit.mjs\`' line trigger is aimed at a source file
// growing past the point where a reader can hold it; this file is not read, it is diffed against
// \`tests/album-corpus-roundtrip.test.ts\`, and splitting it would buy nothing but two files to
// re-emit. The waiver is acknowledged rather than silent.

import type { Temperament } from '../spirit'

/** The album's chapters. ⚠ \`jun\` is not among them: spec §3 and §4b – the band under 11 is
 *  unreachable (the world starts at thirteen) and carried 0 milestones on all nine measured careers,
 *  so chapter 1 is the prologue instead. */
export type AlbumBand = ${union(ALBUM_BANDS)}

/** The family the selector draws an occasion from – the nine \`MilestoneType\`s plus \`prologue\`
 *  (the trace persisted at handover), \`asset\` (\`world.assets\` and its \`boughtWeek\`), \`rare\` (his
 *  super-rare three) and \`closing\` (the three written frames). */
export type AlbumOccasionKind = ${union(ALBUM_KINDS)}

/** ⭐ ONE OCCASION IN ONE VOICE: the three registers, finished. **No placeholders and no
 *  interpolation** – her name is the player's, so the note says «you» and the caption says «she», and
 *  neither ever needs one. The sheet renders the date and her age above the note out of the frame's
 *  own week; no string here writes either, because a corpus cannot know them. */
export interface AlbumHand {
  /** to her, second person – the pasted, torn-edged note */
  note: string
  /** about her, third person – the polaroid's bottom lip */
  caption: string
  /** to nobody – the parent thinking, loose in the margin */
  line: string
}

export interface AlbumOccasion {
  id: string
  kind: AlbumOccasionKind
  bands: readonly AlbumBand[]
  /** \`null\` where the kind alone is the occasion; otherwise the named condition, resolved engine-side. */
  gate: string | null
  voices: Record<Temperament, AlbumHand>
}

/** ⭐ THE ARC – «сначала она была такой-то, а потом стала такой-то» (his addition, 19.09). The voice
 *  key is what she was BORN (\`temperament\`, drawn at birth and never changed); the direction is where
 *  \`wallsLean\` went. ⚠ There is no third direction: spec §4b measured the lean moving on 1 career of
 *  9, and the ruling is that the other eight take the ordinary closing sheet rather than being told
 *  they stayed themselves. ⚠ Two registers, not three – the arc's sentence needs both points in it and
 *  a caption cannot hold two points. */
export type AlbumArcDirection = ${union(ALBUM_ARC_DIRECTIONS)}

export interface AlbumArcHand {
  note: string
  line: string
}

export const ALBUM_CORPUS: readonly AlbumOccasion[] = [
`
  const body = corpus.occasions.flatMap(emitOccasion).join('\n')
  const arcHead = `
export const ALBUM_ARC: Record<AlbumArcDirection, Record<Temperament, AlbumArcHand>> = {
`
  const arcBody = corpus.arc.flatMap(emitArc).join('\n')
  return `${head}${body}\n]\n${arcHead}${arcBody}\n}\n`
}

const text = emit()
if (process.argv.includes('--write')) {
  writeFileSync(OUT, text)
  const counts = albumCounts(readAlbumCorpus())
  console.log(
    `wrote ${OUT.pathname}: ${counts.occasions} occasions, ${counts.notes} notes, ${counts.captions} captions, ` +
      `${counts.lines} lines, ${counts.arcCells} arc cells, ${counts.arcStrings} arc strings`,
  )
} else {
  console.log(text)
}
