/**
 * THE E2E FIXTURE ENGINE – career saves for the Playwright layer, generated by playing.
 *
 * Run:  npm run e2e:fixtures                 (all ten, byte-identical every time)
 *       npm run e2e:fixtures -- --only pro   (one of them; the other nine keep their manifest rows)
 *       npm run e2e:fixtures -- --budget 40  (how many seeds a search may try before it gives up)
 *
 * WHY IT EXISTS. A browser test that wants a career at week 412 cannot click there – it is eight
 * seasons of decisions – and fast-forwarding there costs minutes per test and couples every test to
 * the balance model. So the state is written into IndexedDB before the app boots, and this file
 * makes the bytes. Setup drops from minutes to milliseconds, which is what makes the whole e2e
 * layer affordable (docs/plans/playwright.md §3).
 *
 * ⚠ WHAT THIS FILE IS NOT ALLOWED TO DO, and it is the rule the fixtures live or die by:
 * IT NEVER HAND-EDITS A WORLD. Every state below is REACHED by playing – the engine's own
 * `createWorld`, the shared career loop from tools/econ-bench.ts, and the engine's own answers to
 * the questions the engine raises (`answerFork`). Where a state is rare, the generator SEARCHES
 * SEEDS until a career genuinely arrives at it and records the seed that did. A world poked into
 * shape is a fixture that could not have happened in play, and a test standing on one tests nothing.
 * The one exception is `careerId`, which the engine does not own at all: the worker mints it from
 * `Date.now()` outside the deterministic engine (`makeCareerId`), so the fixtures pin a stable one.
 *
 * ⚠ THE BYTES ARE THE PRODUCT'S OWN. `encodeExportFile` writes them and `decodeExportFile` reads
 * them back before anything is committed to disk – the versioned envelope, the gzip payload and the
 * SHA-256 that guards it. Nothing here re-implements the format, so a fixture cannot disagree with
 * what the app reads. The same file works through the app's "Import from file" door and, sliced at
 * the header, as the IndexedDB record the harness seeds (see `splitEnvelope`).
 *
 * ⚠ ZERO NEW RANDOMNESS ON MAIN. The generator takes no draw of its own: it hands the engine the
 * world's OWN persisted MAIN position (`resumeMain(world.rngMain)` – the serializer rule from
 * tools/demo-save.ts, which a raw `rngFromSeed` tap would break by shipping a week-412 career whose
 * saved stream position says zero), and the only other randomness it touches is the engine's own
 * purpose-scoped `seed:surname` sub-stream for the kid's family name. The frozen MAIN capture
 * cannot see this file.
 *
 * ⚠ THE OWNER'S OWN SAVE IS NEVER A FIXTURE. Generated careers only – it may be read locally for
 * diagnosis and is never committed, derived from or copied here.
 *
 * NOT THE GOLDEN-SAVE CORPUS. `tests/fixtures/saves/vN.json` is one raw world per schema version and
 * exists to prove MIGRATIONS work; these are ten playable STATES at the current version and exist
 * to give a browser somewhere to start. See docs/plans/e2e-fixtures.md §"Two corpora".
 */
import { mkdirSync, readdirSync, writeFileSync } from 'node:fs'
import {
  advanceRefusal,
  answerFork,
  answerRetirement,
  autoEndingViewOf,
  buildTourBriefing,
  createWorld,
  pendingBirthday,
  kidAgeYears,
  kidPoints,
  pendingKnock,
  seasonIndexOf,
  tickWeek,
  SAVE_SCHEMA_VERSION,
  STARTING_FUNDS_CENTS,
  type WorldState,
  answerLifeBeat,
  pendingLifeBeat,
  liveSoftBeat,
  activeEpisode,
  loveEpisodesOf,
  lifeLogOf,
  toSnapshot,
} from '../src/engine/world'
// ⚠ THE MOOD LADDER IS READ OFF THE ENGINE'S OWN TABLE AND NEVER TRANSCRIBED HERE. `MOOD_WORD` is
// the owner's five approved words (invariant 4) and `SPIRIT_BANDS` is the ladder top-down, so the
// rung arithmetic in `moodRung` below moves with the spec instead of drifting away from it.
import { MOOD_WORD, SPIRIT_BANDS } from '../src/engine/spirit'
import { resumeMain, rngFromSeed, pickInt, type Rng } from '../src/engine/rng'
import { decodeExportFile, encodeExportFile, sha256 } from '../src/engine/saveCodec'
import { debtWeeks, ENDINGS } from '../src/engine/ending'
import { activeKitDeal, isSponsorWindowWeek } from '../src/engine/offers'
import { FIRST_NAMES, pickSurname } from '../src/engine/season/cohort'
import { WEEKS_PER_YEAR } from '../src/engine/season/calendar'
import { DEFAULT_PROFILE, type CoachTier, type FamilyBackground, type PlayerProfile } from '../src/shared/protocol'
import { POLICIES, stepCareerWeek, type Policy } from './econ-bench'
import {
  careerIdFor,
  ENVELOPE_HEADER_BYTES,
  FIXTURE_DIR,
  FIXTURE_NAMES,
  MANIFEST_FILE,
  loadManifest as readManifestFile,
  readFixtureBytes,
  slotFor,
  splitEnvelope,
  type FixtureEntry as FixtureRow,
  type FixtureFacts,
  type FixtureManifest as FixtureManifestFile,
  type FixtureName,
} from './e2e-fixtures-read'
import { drainLifeBeats } from './_lifeBeats'
// ⚠ v75 T8 – `belated` REPLAYS THE KNOCK THE SPEC PRESSES, and this is the one helper that decides
// what that press is (`'rest'`, once, everywhere). See that recipe's own note.
import { drainKnock } from './_knocks'

// --- reading (the rot alarm and the Playwright harness both come through here) --------------------
//
// ⚠ THE READER LIVES IN `./e2e-fixtures-read.ts` AND IS RE-EXPORTED HERE UNCHANGED, so this module's
// public surface is exactly what it was and `tests/e2e-fixtures.test.ts` imports the same names from
// the same path. The split is for the BROWSER HARNESS, which needs the manifest and the envelope
// offset and must not drag the engine this file imports into every Playwright worker to get them –
// the reader's own header argues it at length.

export {
  careerIdFor,
  ENVELOPE_HEADER_BYTES,
  FIXTURE_DIR,
  FIXTURE_NAMES,
  MANIFEST_FILE,
  readFixtureBytes,
  slotFor,
  splitEnvelope,
}
export type { FixtureFacts, FixtureName }

/** The manifest row with the engine's own types back on it. The reader carries `background`,
 *  `coachTier` and `policy` as plain strings because their unions live in modules that import the
 *  engine; this side already has those imports, so the generator writes them typed and the rot alarm
 *  reads them typed – `STARTING_FUNDS_CENTS[entry.background]` is an index, and it has to be. */
export interface FixtureEntry extends FixtureRow {
  background: FamilyBackground
  coachTier: CoachTier
  policy: Policy['id']
}

export interface FixtureManifest extends FixtureManifestFile {
  fixtures: FixtureEntry[]
}

export function loadManifest(): FixtureManifest {
  return readManifestFile() as FixtureManifest
}

/** Everything a spec asserts on, read off a world. The single definition – the generator writes the
 *  manifest with it and the rot alarm re-derives with it, so the two cannot drift apart. */
export function factsOf(world: WorldState): FixtureFacts {
  const domesticPoints = kidPoints(world, 'domestic')
  const itfPoints = kidPoints(world, 'itf')
  const wtaPoints = kidPoints(world, 'wta')
  return {
    week: world.week,
    seasonIndex: seasonIndexOf(world.week),
    ageYears: kidAgeYears(world.week, world.profile.birthMonth, world.profile.birthDay),
    fundsCents: world.fundsCents,
    kidRank: world.kidRank,
    rankedDomestic: domesticPoints > 0,
    rankedItf: itfPoints > 0,
    rankedWta: wtaPoints > 0,
    domesticPoints,
    itfPoints,
    wtaPoints,
    seasonsPlayed: world.seasonHistory.length,
    resultRows: world.results.length,
    feedEvents: world.events.length,
    financeWeeks: world.financeWeeks.length,
    cohortSize: world.cohort.length,
    endingType: world.ending ? world.ending.type : null,
    debtWeeks: debtWeeks(autoEndingViewOf(world)),
    inSponsorWindow: isSponsorWindowWeek(world.week),
    openKitLetters: world.offers.filter((o) => o.kind === 'kit' && o.state === 'open').length,
    hasActiveKitDeal: activeKitDeal(world.offers, world.week) !== null,
    rngMain: { s: world.rngMain.s, n: world.rngMain.n },
  }
}

// --- generation -----------------------------------------------------------------------------------

/** A career the fixtures can start: the engine's own `createWorld`, plus the two things the engine
 *  deliberately does not own – a stable careerId (the worker mints one from `Date.now()`) and a name
 *  drawn from the shipped pools, never invented here.
 *
 *  ⚠ `resumeMain(world.rngMain)`, NOT `rngFromSeed(world.seed)`. This file SERIALIZES, and the two
 *  differ exactly there: both produce the same draws, but only the resumed generator writes the
 *  position back onto the world, so the exported career carries a TRUE `rngMain`. A raw tap would
 *  ship a week-412 save claiming zero draws spent, and the app would replay them on load. The same
 *  ruling is written out at length in tools/demo-save.ts; the benches, which never serialize, keep
 *  their raw taps. */
function openFixtureCareer(
  name: FixtureName,
  seed: string,
  background: FamilyBackground,
  coachTier: CoachTier,
  policy: Policy,
): { world: WorldState; rng: Rng } {
  // Her name comes out of the engine's own pools through a purpose-scoped sub-stream – the same
  // door onboarding's 🎲 uses. Nothing here may invent a surname: the pools are curated so that no
  // real player's name is constructible (see the SURNAMES note in season/cohort.ts), and a fixture
  // that made up its own would quietly leave that guarantee behind.
  const nameRng = rngFromSeed(`${seed}:e2e-given-name`)
  const profile: PlayerProfile = {
    ...DEFAULT_PROFILE,
    kidName: FIRST_NAMES[pickInt(nameRng, 0, FIRST_NAMES.length - 1)],
    kidLastName: pickSurname(seed),
    background,
    coachTier,
  }
  const world = createWorld(seed, profile, careerIdFor(name))
  world.coachOnEventWeeks = policy.coachOnEventWeeks
  return { world, rng: resumeMain(world.rngMain) }
}

/** Answer whatever the engine has asked, the way tools/endings-bench.ts does – the fork at nineteen
 *  and the retirement offer are QUESTIONS, and a career that never answers them stops there.
 *  `fork` is the recipe's stance; the retirement offer cannot fire before 29 and is handled for
 *  completeness (refuse until the game stops asking, which keeps a career playing). */
function answerOpenQuestions(world: WorldState, fork: 'continue' | 'college' | 'stop'): void {
  // ⭐ v73: her opinion of the fork is raised by the tick that opens it, and `answerFork`
  // refuses until it is answered. ⚠ RE-AIMED v74 from `answerLifeBeat(world, 'listen')`, which
  // stopped being a complete answer when `'met'` landed – see `tools/_lifeBeats.ts`. The intent is
  // the one this line always had: a caller that never asked the player must not put a number on
  // the scale, so every row takes the bond-neutral answer of its OWN kind.
  drainLifeBeats(world)
  if (world.fork !== null && world.fork.answer === null) answerFork(world, fork)
  if (world.retirementOffer !== null) answerRetirement(world, world.retirementOffer.final)
}

interface Recipe {
  name: FixtureName
  purpose: string
  background: FamilyBackground
  coachTier: CoachTier
  policy: Policy
  fork: 'continue' | 'college' | 'stop'
  /** walk the career; return the reason it was rejected, or null when this seed is the fixture */
  drive: (world: WorldState, rng: Rng, recipe: Recipe) => string | null
}

const GRINDER = POLICIES[0]
const PLAYER = POLICIES[1]

/** Play forward to `until`, answering every question on the way. Stops early if the career ends. */
function playTo(world: WorldState, rng: Rng, recipe: Recipe, until: number): void {
  while (world.week < until && world.ending === null) {
    // ⚠ `drainKnocks: false` – THIS TOOL MEASURES THE KNOCK. The `junior` recipe demands a save
    // that BOOTS holding an unanswered one and three recipes reject a seed that grows one, so the
    // shared drain (`tools/_knocks.ts`, wave 3 point 5) must not reach this walk: with it on, 200
    // of 200 junior seeds were rejected with «boots without an open knock». The T6b law, at the
    // one site where it arrives through a helper rather than through a call of its own.
    stepCareerWeek(world, rng, recipe.policy, undefined, { drainKnocks: false })
    answerOpenQuestions(world, recipe.fork)
  }
}

/** ~week 412 – old enough that the ledgers are full, and week 412 % 52 = 48 puts her inside the
 *  five-week sponsor window by construction. */
const PRO_WEEK = 412
/** ~week 120 – the middle of her third season, by which a junior who is going to be ranked is. */
const JUNIOR_WEEK = 120
/** One week short of the latch. `bankruptcyDue` fires at ENDINGS.bankruptcyGraceWeeks consecutive
 *  weeks under water, and a spell reaches 12 only by passing through 11 – so this is the last week
 *  the family is still standing on the wrong side of the money, which is the state the warning
 *  phase exists for. */
const BROKE_DEBT_WEEKS = ENDINGS.bankruptcyGraceWeeks - 1
/** HALFWAY DOWN THE SAME SLOPE, and the halving is what the fixture is for rather than a number
 *  somebody liked. `broke` sits on the last week before the latch, so the advance that would show a
 *  player the warning INSTEAD ends the career – measured, in e2e/week-advance.spec.ts, by writing
 *  that spec and watching it fail on the epilogue. A fixture whose next tick is still an ordinary
 *  week needs weeks in hand on both sides: enough spent under water that the countdown is real
 *  (not week one of a spell), and enough left that nothing latches. `graceWeeks / 2` is the only
 *  point that is maximally far from both ends, and it moves with the constant instead of drifting
 *  away from it the next time the grace window is retuned. */
const SINKING_DEBT_WEEKS = Math.floor(ENDINGS.bankruptcyGraceWeeks / 2)
/** The fork is her nineteenth birthday week – five seasons and a bit. The cap is generous so a late
 *  birthday still lands inside it. */
const FORK_CAP_WEEK = 6 * WEEKS_PER_YEAR
/** ⭐ HOW LONG `soft` WAITS FOR HER TO COME BY, AND THE NUMBER IS THE HAZARD'S RATHER THAN A ROUND
 *  ONE. Tier 1 rolls every week from week 0 with no age gate, at 4% a week at `steady` and 8% at
 *  `close` (`ECONOMY.life.smallTalkPerWeek`), so one season is already `1 − 0.96^52` ≈ **88%** of
 *  seeds on the slower of the two bands – and a seed that brings nothing in a whole season is a
 *  career whose bond sat in `strained`/`cold`, where the chance is priced at ZERO and the silence is
 *  the design («none at cold; the silence is still the line», who-she-is §5b). That is a different
 *  fixture, not a slow one, so the walk says so and the search moves on. */
const SOFT_CAP_WEEK = WEEKS_PER_YEAR
/** ⭐ HOW LONG THE TWO ENDING RECIPES WAIT, AND THE NUMBER IS THE TWO HAZARDS' ARITHMETIC RATHER THAN
 *  A ROUND ONE. Nobody can arrive before SIXTEEN (`arrivalEligible`, ⭐ RULED 23.08), which is week
 *  156 of a career that opens at thirteen; after that an arrival waits `1 / (0.025 × MULT)` weeks and
 *  the attachment it starts waits `1 / (0.012 × endsMult)` more. On the FAST rows of who-she-is §4's
 *  two columns that is 156 + 25 + 55 ≈ 236 for a fiery girl and 156 + 80 + 92 ≈ 328 for a deep one;
 *  on the slow one (quiet: arrival ×0.6, ends ×0.35) it is past 450 – and a career that has to be
 *  walked that far is a SLOWER SEED, not a longer walk, because the search costs one career per try
 *  and the walk costs every career the same. Eight seasons is where the two fast rows are both inside
 *  and the third is deliberately left to the seed budget.
 *  ⚠ IT IS THE CAP FOR BOTH, because the told-late scene is the same two hazards with a lag drawn
 *  between them – `belated` cannot be reached any earlier than `breakup` and is rarer, never sooner. */
const ENDS_CAP_WEEK = 8 * WEEKS_PER_YEAR

/** ⭐ THE ANSWER BOTH LOOK-AHEADS PRESS, AND IT IS THE ONE e2e/breakup.spec.ts PRESSES TOO.
 *
 *  ⚠ IT IS **NOT** `DRAIN_ANSWER['ended']` AND MUST NOT BE. The drain's answer is `'fix-it'`, chosen
 *  because it is READ-INDEPENDENT (−1 under both readings, wave-4 brief §0.2) – that is a property a
 *  harness needs and a player does not. What a look-ahead has to do is press what the SPEC presses,
 *  because the whole claim of the look-ahead is that the week the browser reaches is the week that was
 *  measured. `'space'` is the first of the four on the card, which is the one a reader of the spec
 *  will recognise; its PRICE differs by the read (+3 matched / −3 mismatched) and neither this file
 *  nor the spec looks at the price, so the flip cannot make either of them wrong. */
const ENDS_ANSWER_ID = 'space'

/** ⭐⭐⭐ HAS THIS EPISODE ALREADY PRODUCED A BEAT, AND OF WHICH KINDS – RULING A's OWN DISCRIMINATOR,
 *  asked from outside the engine.
 *
 *  ⚠⚠ THE REGISTER IS THE `'met'` RECEIPT AND **NEVER** `endedWeek < knownWeek`, which is the one
 *  thing a reader of these two recipes could get wrong and the reason this helper is written out
 *  rather than inlined twice. The engine decides told-now vs told-late by asking whether a `'met'`
 *  row for the episode exists (`beatEndsRegister`, world/lifeBeat.ts), and the two readings disagree
 *  on exactly the week where `endedWeek === knownWeek` – which is reachable, and on which the literal
 *  rule produces the defect ruling A was written to prevent. A generator that classified its own
 *  fixtures by the OTHER rule would accept a career for a scene the browser then never shows.
 *
 *  ⚠ IT IS `lifeLogOf` AND NOT A SECOND LEDGER: the log IS the receipt («the record IS the queue»),
 *  and the answer on the row is irrelevant – a drained `'met'` is still a `'met'`, which is what lets
 *  `breakup`'s walk go past the arrival card through `answerOpenQuestions` and still be a career the
 *  parent was told about. */
function hasBeatFor(world: WorldState, episodeId: string, kinds: readonly string[]): boolean {
  return lifeLogOf(world).some((row) => kinds.includes(row.kind) && row.detail === episodeId)
}

/** ⭐⭐ WHICH RUNG OF THE MOOD LADDER THE KID SCREEN WOULD BE SHOWING, 0 = `Glowing` … 4 = `Heavy`,
 *  and **−1 when the tile is not speaking a spirit word at all**.
 *
 *  ⚠⚠ THE −1 IS THE LOAD-BEARING HALF AND IT IS A FACT ABOUT THE PRODUCT, not defensive coding.
 *  `DiaryFacts.moodWord` is `null` on every week the BODY channel wins the diary (engine/diary.ts:
 *  `channel === 'mood' ? MOOD_WORD[…] : null`), and KidScreen then falls back to the face's own word
 *  – `Tired`, `Hurt`, `On the mend`. So «the Mood word dropped a rung» is a claim that is not even
 *  well-formed on such a week, and a fixture parked on one would hand e2e/breakup.spec.ts two words
 *  off two different ladders to compare. The recipe rejects the seed instead of hoping.
 *
 *  ⚠ IT GOES THROUGH `toSnapshot`, WHICH IS THE WIRE THE BROWSER ACTUALLY READS – not
 *  `spiritBandOf(world.spirit)`, which would be a second spelling of the same question and would miss
 *  the channel decision entirely. A fixture accepted here is a fixture whose tile the browser will
 *  really see move. */
function moodRung(world: WorldState): number {
  const word = toSnapshot(world).diary.facts.moodWord
  return word === null ? -1 : SPIRIT_BANDS.findIndex((band) => MOOD_WORD[band] === word)
}

const RECIPES: Recipe[] = [
  {
    name: 'fresh',
    purpose: 'A career the week it was created – the boot path, onboarding and the empty screens.',
    background: 'middle',
    coachTier: 'middle',
    policy: PLAYER,
    fork: 'continue',
    // Nothing to search: week 0 IS createWorld's output, and it is a real saved state because the
    // worker adopts an autosave the moment a career is made.
    drive: (world) => (world.week === 0 && world.ending === null ? null : 'not a week-0 world'),
  },
  {
    name: 'junior',
    purpose: 'First ranking earned – the junior ladder, the standings, a feed with something in it.',
    background: 'middle',
    coachTier: 'middle',
    policy: PLAYER,
    fork: 'continue',
    drive: (world, rng, recipe) => {
      playTo(world, rng, recipe, JUNIOR_WEEK)
      if (world.ending !== null) return `career ended (${world.ending.type}) before week ${JUNIOR_WEEK}`
      // ⚠ A RANKING, ON WHATEVER TABLE SHE EARNED ONE – AND THE CHANGE OF WORD IS A MEASUREMENT
      // (16.08). This clause read `kidPoints(world, 'domestic') <= 0` and after this wave no seed in
      // 120 could satisfy it together with the other two: at week 120 only **46 of 120** careers hold
      // domestic points, while **114 of 120** hold ITF ones.
      //
      // ⚠⚠ AND THE FIRST READING OF THAT WAS WRONG, WHICH IS WHY IT IS WRITTEN OUT RATHER THAN
      // QUIETLY FIXED. It said "her first ranking is now the ITF one". P6 measured it properly on the
      // frozen battery and the opposite is true: **90 careers of 90 earn a domestic ranking, all of
      // them at 13.6, and in 90 of 90 it is her FIRST** – the ITF one is never first. What the 46 of
      // 120 actually shows is DECAY, not absence: domestic points live in a rolling 52-week window,
      // 100% of careers hold one at 14.6 and half still do at 15.8, and by week 120 many have simply
      // aged out. A fixture recipe is exactly the wrong place for a claim about the ladder, and this
      // is what that costs – see docs/specs/the-remeasure-2026-08.md.
      //
      // The SPEC'S claim is unchanged, and that is why this is a re-aim rather than a weakening:
      // e2e/seeded-careers.spec.ts says in its own comment that the point is "a fact that no week-0
      // career could hold and that lives deep inside the payload" – she is ranked, and the ladder says
      // so. Which of the three tables carries it was the vehicle, never the claim.
      if (kidPoints(world, 'domestic') <= 0 && kidPoints(world, 'itf') <= 0 && kidPoints(world, 'wta') <= 0)
        return 'never earned a ranking on any table'
      if (world.seasonHistory.length < 2) return 'fewer than two seasons behind her'
      // ⚠ AND SHE MUST BOOT HOLDING AN OPEN KNOCK, which is a REQUIREMENT of this fixture rather
      // than a lucky property of it (11.08). `e2e/week-advance.spec.ts` uses this career to prove
      // that a real worker's real world state disables the week button - the engine refuses to
      // advance while `pendingKnock` holds, and the UI has to show that refusal BEFORE the player
      // presses anything. No other fixture can carry that claim: it needs a live, un-answered
      // decision sitting on a bootable save.
      //
      // It used to hold one by accident, and this wave's schema bump regenerated the corpus and took
      // it away - CI went red on that one spec with every unit test green. The spec's own failure
      // message named both remedies ("move this canary to a fixture that does, or teach
      // tools/e2e-fixtures.ts to search for one"), and the owner chose the search: a seed filter
      // survives the NEXT regeneration, a relocated canary only survives until the next one.
      //
      // The search is free - the loop already tries `budget` seeds and prints why each was rejected,
      // so this is one more clause in a predicate that was always there, not a new mechanism.
      if (!pendingKnock(world)) return 'boots without an open knock (week-advance.spec needs one)'
      // ⚠ AND SHE MUST BE ENTERED FOR THE WEEK AHEAD, for exactly the same reason and by exactly the
      // same history (16.08). `e2e/tournament.spec.ts` and `persistence.spec.ts`'s mid-reveal case
      // both tick this career once and then wait for `Begin` – a tournament reveal – and neither can
      // get one unless the tick lands on an event she has entered. persistence.spec even states the
      // assumption in prose ("She is entered for the week ahead, so this tick computes the whole
      // draw"), which is how a property nobody enforced survived three waves: it was TRUE of the
      // seed the search happened to stop on, and P1's junior-access change moved the search.
      //
      // Same remedy the owner chose for the knock, for the same stated reason – a seed filter
      // survives the NEXT regeneration, a relocated assertion only survives until the next one.
      const weekAhead = world.season.filter((e) => e.week === world.week + 1)
      if (!weekAhead.some((e) => world.entries.includes(e.id)))
        return 'not entered for the week ahead (tournament.spec + persistence.spec need a reveal)'
      return null
    },
  },
  {
    name: 'pro',
    purpose: 'Eight seasons in, inside the sponsor window, ledgers full – the heavy-state screens.',
    background: 'middle',
    coachTier: 'middle',
    policy: PLAYER,
    fork: 'continue',
    drive: (world, rng, recipe) => {
      playTo(world, rng, recipe, PRO_WEEK)
      if (world.ending !== null) return `career ended (${world.ending.type}) before week ${PRO_WEEK}`
      if (world.week !== PRO_WEEK) return `stalled at week ${world.week}`
      if (!isSponsorWindowWeek(world.week)) return 'not inside the sponsor window'
      // ⚠ THE PROFESSIONAL TABLE, NOT THE JUNIOR ONE. At twenty-two her ITF (junior) points are
      // long gone – the J rungs cap at 18 and the tables are a rolling 52 weeks – so asking for
      // `itf` points here rejects every career that ever grew up. Three tables, three currencies.
      if (kidPoints(world, 'wta') <= 0) return 'unranked professionally'
      if (world.financeWeeks.length === 0) return 'no finance ledger'
      // The sponsor spec needs paper on the table: either a letter she can open and sign, or a deal
      // already running that the money screen can show.
      const openLetters = world.offers.filter((o) => o.kind === 'kit' && o.state === 'open').length
      if (openLetters === 0 && activeKitDeal(world.offers, world.week) === null) return 'no kit letter and no live deal'
      return null
    },
  },
  {
    name: 'sinking',
    // The same corridor and the same reckless arm as `broke`; the only difference is where the walk
    // is stopped. See SINKING_DEBT_WEEKS for why halfway, and for the measurement that made a second
    // fixture on one slope the right answer rather than a duplicate.
    purpose: 'Under water with weeks in hand – the warning a career can still be ticked out of.',
    background: 'working',
    coachTier: 'middle',
    policy: GRINDER,
    fork: 'continue',
    drive: (world, rng, recipe) => {
      // Deliberately the same walk as `broke`, stopping earlier. Every spell that reaches the latch
      // passes through this week too, so the state is on the way to bankruptcy rather than staged
      // beside it – and the career still has room to be advanced without ending.
      while (world.week < FORK_CAP_WEEK && world.ending === null) {
        stepCareerWeek(world, rng, recipe.policy, undefined, { drainKnocks: false })
        answerOpenQuestions(world, recipe.fork)
        if (debtWeeks(autoEndingViewOf(world)) === SINKING_DEBT_WEEKS) {
          // ⚠ AND THE WEEK AFTER THIS ONE MUST NOT RAISE A KNOCK (16.08). e2e/week-advance.spec.ts's
          // stop-notice journey ticks this career once and then asserts that the banner SURVIVES a
          // change of screen – and a knock raised by that tick breaks the claim in a way the spec has
          // no business working around. It is a real modal, so it blocks `Proceed to Home`; and
          // answering it is a COMMAND, which produces a fresh snapshot, and `stopReasons` die with
          // the advance that produced them by design (App.vue, Package N). So the banner is correctly
          // gone, the assertion is correctly red, and neither is a defect.
          //
          // ⚠ THE LOOK-AHEAD IS EXACT, NOT AN ESTIMATE. The clone carries `rngMain`, so resuming MAIN
          // from it walks the same sequence the browser will walk; `tickWeek` is what the worker runs
          // behind the week button. Nothing about the fixture's own world is touched.
          const probe = structuredClone(world)
          tickWeek(probe, resumeMain(probe.rngMain))
          if (pendingKnock(probe)) return 'a knock lands on the very next week (the stop-notice journey needs a clean tick)'
          return null
        }
      }
      return world.ending !== null
        ? `career ended (${world.ending.type}) without a ${SINKING_DEBT_WEEKS}-week spell`
        : 'never spent that long under water'
    },
  },
  {
    name: 'broke',
    // The reckless arm on the tightest corridor – the cell the econ bench measures going under.
    purpose: 'Eleven weeks under water, one week short of the bankruptcy latch – the warning phase.',
    background: 'working',
    coachTier: 'middle',
    policy: GRINDER,
    fork: 'continue',
    drive: (world, rng, recipe) => {
      // Walk week by week and stop the moment the spell is one week short of the latch. Every spell
      // that ever reaches the grace window passes through this week, so the state is found rather
      // than constructed – and stopping here leaves the career still alive and still refusable.
      while (world.week < FORK_CAP_WEEK && world.ending === null) {
        stepCareerWeek(world, rng, recipe.policy, undefined, { drainKnocks: false })
        answerOpenQuestions(world, recipe.fork)
        if (debtWeeks(autoEndingViewOf(world)) === BROKE_DEBT_WEEKS) {
          return null
        }
      }
      return world.ending !== null
        ? `career ended (${world.ending.type}) without a ${BROKE_DEBT_WEEKS}-week spell`
        : 'never spent that long under water'
    },
  },
  {
    name: 'ending',
    purpose: 'Past the fork at nineteen, racket down – the epilogue, the album and a read-only career.',
    background: 'middle',
    coachTier: 'middle',
    policy: PLAYER,
    fork: 'stop',
    drive: (world, rng, recipe) => {
      // The fork is a QUESTION the engine raises on her nineteenth birthday week, and 'stop' is one
      // of the three answers a player can tap. Answering it is play; nothing is written by hand.
      playTo(world, rng, recipe, FORK_CAP_WEEK)
      if (world.ending === null) return 'the fork never came'
      if (world.ending.type !== 'stopped') return `ended as ${world.ending.type}, not at the fork`
      return null
    },
  },
  {
    name: 'unheard',
    // The state the engine has its own word for: `FORK_UNHEARD_REFUSAL` – «She has said what she
    // wants and nobody has answered her». See FIXTURE_NAMES in tools/e2e-fixtures-read.ts for why
    // this is a second fixture on `ending`'s own week rather than a variant of it.
    purpose:
      'The week a life beat stops – she has said what she wants at the fork and nobody has answered her yet.',
    background: 'middle',
    coachTier: 'middle',
    policy: PLAYER,
    // ⚠ THIS STANCE IS NEVER USED BY THE WALK, because the walk stops before `answerOpenQuestions`
    // ever reaches the fork. It is what the LOOK-AHEAD below answers with, and it is `'continue'`
    // because that is the one answer of the three that leaves a career to go on playing – the other
    // two end it or freeze it, and the spec presses the week button afterwards.
    fork: 'continue',
    drive: (world, rng, recipe) => {
      while (world.week < FORK_CAP_WEEK && world.ending === null) {
        stepCareerWeek(world, rng, recipe.policy, undefined, { drainKnocks: false })
        // ⚠⚠ v74 T15 – AND TIER 1 IS NO LONGER AMONG WHAT THIS LINE ANSWERS, which is why the note
        // below reads as history. A `'small-talk'` row is declared NON-BLOCKING (§5b's soft surface,
        // ruled 11.09), so it is not pending, this drain never sees one, and the recipe's own clause
        // below cannot be tripped by one either – the rows simply ride along in `lifeLog`, unanswered
        // and harmless, exactly as they do in a played career. The call STAYS: `'met'` still raises
        // and still blocks, and this recipe must walk past one without answering the fork.
        // ⚠⚠ v74 (wave 3, T8) – TIER-1 SMALL TALK IS ANSWERED ON THE WAY PAST, AND IT HAD TO BE.
        // T8 raises a `'small-talk'` row on up to 8% of weeks from week 0, so on nearly every seed
        // the FIRST pending row this loop met was tier 1 and the clause below rejected it: measured,
        // `unheard` reported «no seed in 200 reached the state» with 199 of them reading «the fork is
        // not open behind her» at weeks 1-68. Answering it here is what every OTHER recipe in this
        // file already does through `answerOpenQuestions`, and the answer is the BOND-NEUTRAL one, so
        // the fixture's numbers are the ones a career that was never asked would have had.
        // ⚠ THE LIST KEEPS BOTH OF THE KINDS THIS RECIPE MUST NOT ANSWER: the fork's own row is what
        // it is hunting, and a `'met'` row is a seed it deliberately REJECTS four clauses down.
        drainLifeBeats(world, ['fork-opinion', 'met'])
        // ⚠⚠ THE CHECK SITS BEFORE THE ANSWER, AND THAT ONE LINE IS THE WHOLE RECIPE. Every other
        // career in this file walks through `answerOpenQuestions`, whose FIRST clause drains the
        // beat on the way past (v74: `drainLifeBeats`, which was `answerLifeBeat(world, 'listen')`
        // while `'fork-opinion'` was the only kind) – so no committed fixture could ever boot holding
        // a pending one, and e2e/life-beat.spec.ts had nowhere to start. This stops the walk on the
        // tick that raised her row instead of one line later. Nothing is hand-written: the state is
        // reached by playing, exactly as every other recipe reaches its own.
        if (pendingLifeBeat(world) !== null) {
          // ⚠ HER DIALOG HAS TO BE THE ONE ON SCREEN, AND THE QUEUE ABOVE IT DECIDES THAT.
          // `blockingOverlay` shows a knock and a birthday FIRST and holds every question behind a
          // tournament reveal, so a career that boots holding any of the three boots into somebody
          // else's card and the spec would be asserting about a dialog it never reached. Same
          // seed-filter remedy the owner chose for `junior`'s open knock, for the same stated
          // reason: a clause here survives the NEXT regeneration, a spec that steps around it
          // survives only until the one after.
          if (pendingKnock(world)) return 'boots holding a knock, which outranks her in the queue'
          if (pendingBirthday(world) !== null) return 'boots holding a birthday, which outranks her in the queue'
          if (world.pendingTournament) return 'boots into a tournament reveal, which holds her card back'
          // ⚠ AND THE BRIEFING, which is not in that queue but is a blocking card all the same: it
          // is withheld while a question is pending and lands the moment the last one is answered,
          // which in this career is the fork. It would arrive in the middle of the spec's walk.
          if (buildTourBriefing(world) !== null) return 'the tour briefing is owed, and would land the moment the fork is answered'
          // ⭐ AND THE FORK IS STANDING BEHIND HER. The second half of the case is that answering
          // her is what lets the fork be answered at all, and a beat with no fork behind it could
          // not show that. Guaranteed by the engine – the fork's opening tick raises the row – so
          // this is the clause that would notice if that ever stopped being true.
          if (world.fork === null || world.fork.answer !== null) return 'the fork is not open behind her'
          // ⚠⚠ AND THE ROW WAITING MUST BE HER OPINION OF THAT FORK, WHICH IS NOT THE SAME CLAIM. The
          // look-ahead below presses `'back'` – a fork-opinion answer – and the engine deliberately
          // REFUSES an option the pending row never offered. So a `'met'` row raised in the same week
          // the fork opens would sit first in the queue and make that line THROW, killing the whole
          // generator instead of rejecting one seed.
          //
          // ⚠ WAVE 3 IS WHAT MADE THIS REACHABLE: the arrival hazard can raise a beat on any week from
          // her sixteenth on, where wave 2 had exactly one beat kind and it fired at the fork. The
          // clause directly above rejects nearly every `'met'`-first seed as a side effect, but NOT one
          // that lands on the fork's own week – that is the gap, and it is the difference between a
          // filtered seed and a dead generator. Found by the T6b tools repair and closed here (11.09);
          // it did not bite on the current seeds, which is exactly why it is worth a clause rather
          // than a note.
          if (pendingLifeBeat(world)?.kind !== 'fork-opinion') return 'the row waiting is not her opinion of the fork'

          // ⚠ AND BOTH ANSWERS TOGETHER MUST LEAVE AN ORDINARY WEEK. e2e/life-beat.spec.ts closes by
          // pressing the week button and reading the next week off the screen, so a tick that opened
          // a tournament reveal would replace the surface it reads, and a knock would stop the week
          // again for a reason that is not this wave's.
          //
          // ⚠ THE LOOK-AHEAD IS EXACT, NOT AN ESTIMATE – `sinking`'s own precedent, one recipe up.
          // The clone carries `rngMain`, so resuming MAIN from it walks the sequence the browser
          // will walk, and the two answers below are the two the spec presses. Nothing about the
          // fixture's own world is touched.
          const probe = structuredClone(world)
          answerLifeBeat(probe, 'back')
          // ⭐⭐⭐ v74 T17 – AND ANSWERING HER CAN NOW RAISE ANOTHER CARD IN FRONT OF THE FORK. When the
          // want she stated is `'stop'`, recording the parent's answer raises `'fork-counsel'` – the
          // coach's read, blocking – and `answerFork` on the next line would THROW
          // (`FORK_UNHEARD_REFUSAL`), killing the generator instead of rejecting one seed. That is
          // the same shape as the `'met'`-on-the-fork-week gap four clauses up, and it is closed the
          // same way: this is the REJECTION CLAUSE, and it doubles as the look-ahead learning the
          // beat, because it asks the ENGINE what is standing there rather than listing the kinds
          // that could be. Wave 5's psychologist raises a second such row beside the coach's and is
          // covered the day it is declared.
          //
          // ⚠⚠ AND IT HAS TO BE A REJECTION AND NOT A DRAIN. `e2e/life-beat.spec.ts` presses her
          // answer and then reads the FORK's three buttons off the very next snapshot; a counsel card
          // between them would put the spec in front of a dialog it knows nothing about. Draining the
          // row here would hide that from the generator and move the failure into Playwright.
          const raisedByAnswering = pendingLifeBeat(probe)
          if (raisedByAnswering !== null) {
            return `answering her raises a '${raisedByAnswering.kind}' card in front of the fork, and the spec presses straight past it`
          }
          answerFork(probe, recipe.fork)
          const stillBlocked = advanceRefusal(probe)
          if (stillBlocked !== null) return `answering both leaves a '${stillBlocked}' standing in the week's way`
          tickWeek(probe, resumeMain(probe.rngMain))
          if (probe.ending !== null) return `the week after the fork ends the career (${probe.ending.type})`
          if (probe.pendingTournament) return 'the week after the fork opens a tournament reveal'
          if (pendingKnock(probe)) return 'a knock lands on the week after the fork'
          return null
        }
        answerOpenQuestions(world, recipe.fork)
      }
      return world.ending !== null
        ? `career ended (${world.ending.type}) before the fork opened`
        : 'the fork never opened'
    },
  },
  {
    name: 'soft',
    // ⭐⭐⭐ v74 T15 – THE TIER-1 CAREER: she came by with something small, and the week did not stop
    // for it. See FIXTURE_NAMES in tools/e2e-fixtures-read.ts for the measurement that made this an
    // eighth fixture rather than a flag on one of the seven.
    purpose:
      'She came by with something small – a live, unanswered tier-1 row on a week the engine never stopped.',
    background: 'middle',
    coachTier: 'middle',
    policy: PLAYER,
    // ⚠ NEVER REACHED BY THIS WALK EITHER, and for the opposite reason to `unheard`'s: the search
    // stops on the first live soft row, which lands years before her nineteenth birthday. It is
    // `'continue'` so that a seed which somehow walked that far would still leave a career playing.
    fork: 'continue',
    drive: (world, rng, recipe) => {
      while (world.week < SOFT_CAP_WEEK && world.ending === null) {
        stepCareerWeek(world, rng, recipe.policy, undefined, { drainKnocks: false })
        // ⚠ EVERY BLOCKING QUESTION IS ANSWERED ON THE WAY PAST AND TIER 1 IS NOT ONE OF THEM. This
        // is the ordinary `answerOpenQuestions`, whose `drainLifeBeats` reads `pendingLifeBeat` –
        // BLOCKING rows only since T15 – so a `'small-talk'` row rides along untouched and the loop
        // below is what stops on it. That is the whole difference between this recipe and the six
        // that walk past the same rows without noticing them.
        answerOpenQuestions(world, recipe.fork)

        // ⭐⭐⭐ THE STATE, AND IT IS THE ENGINE'S OWN PREDICATE THAT DECIDES IT. `liveSoftBeat` is
        // what `buildSoftBeatInvite` asks, which is what `snapshot.softBeat` carries, which is what
        // Home's card is drawn from – so a fixture accepted here is a fixture whose card the browser
        // will really see. Nothing is hand-written: the row was raised by `rollSmallTalk` on a week
        // this career actually lived.
        const row = liveSoftBeat(world)
        if (row === null) continue

        // ⚠⚠ AND NOTHING MAY BE STANDING IN FRONT OF THE HUB. The card lives ON Home, under her
        // photograph, and `showSoftBeat` (src/App.vue) is gated on `overlay.value === null` – so a
        // career that boots into ANY blocking question boots into somebody else's card with the
        // invitation sitting unreachable behind it. Same seed-filter remedy `unheard` takes for the
        // same stated reason: a clause here survives the NEXT regeneration, a spec that steps around
        // a bad seed survives only until the one after.
        if (pendingLifeBeat(world) !== null) return 'boots holding a blocking beat, whose card covers the hub'
        if (pendingKnock(world)) return 'boots holding a knock, which is a blocking overlay over Home'
        if (pendingBirthday(world) !== null) return 'boots holding a birthday, which is a blocking overlay over Home'
        if (world.pendingTournament) return 'boots into a tournament reveal, which holds the hub back'
        // ⚠ AND THE BRIEFING, which is not in `blockingOverlay`'s list but is a blocking card all the
        // same – `unheard`'s own clause, for the same reason it has one.
        if (buildTourBriefing(world) !== null) return 'the tour briefing is owed and would land over the hub'

        // ⭐⭐⭐ AND THE WEEK IS **NOT** STOPPED, WHICH IS THE WHOLE CLAIM OF TIER 1 AND THEREFORE OF
        // THIS FIXTURE. `advanceRefusal` is the engine's own answer to «may time move» – the same
        // predicate `advanceWeeks` guards on – and a soft row is deliberately absent from it
        // (`pendingLifeBeat` reads blocking rows only). A seed parked behind ANY other refusal would
        // hand e2e/soft-beat.spec.ts a week button it could not press, and the spec would then be
        // unable to tell «soft never stops the week» from «this career was stopped for something
        // else», which is the one thing it exists to say.
        const refusal = advanceRefusal(world)
        if (refusal !== null) return `the week is stopped by '${refusal}' – this fixture's whole claim is that it is not`

        // ⚠⚠ AND THE ROW MUST STILL BE LIVE ON THE WEEK THE SPEC READS IT BACK AT, WHICH IS ONE TICK
        // LATER. The window is DERIVED (`ECONOMY.life.smallTalkTtlWeeks`, 3 = the raise week and the
        // two after it) and `liveSoftBeat` recomputes it from `week − row.week` every time it is
        // asked – so a career parked ON the raise week is live now and says nothing about being live
        // after the press. The spec's second step is «the week moved and she is still waiting», which
        // is «never lost» seen from the hub, and it needs that to be a PROPERTY of the fixture rather
        // than a hope about a constant.
        //
        // ⚠ THE LOOK-AHEAD IS EXACT, NOT AN ESTIMATE – `sinking`'s and `unheard`'s own precedent. The
        // clone carries `rngMain`, so resuming MAIN from it walks the sequence the browser will walk
        // and `tickWeek` is what the worker runs behind the week button. Nothing about the fixture's
        // own world is touched.
        const probe = structuredClone(world)
        tickWeek(probe, resumeMain(probe.rngMain))
        const after = liveSoftBeat(probe)
        if (after === null || after.week !== row.week)
          return `her row is not live any more one week on (smallTalkTtlWeeks would have to be > ${probe.week - row.week})`
        // AND THE WEEK THE PRESS REACHES IS AN ORDINARY ONE. The spec reads the new week off the
        // screen with the card still on it, so a tick that ended the career, opened a reveal or
        // raised a blocking question would replace the surface it is reading – and a blocking beat in
        // particular would put a modal over the very card the next step goes on to tap.
        if (probe.ending !== null) return `the week after ends the career (${probe.ending.type})`
        if (probe.pendingTournament) return 'the week after opens a tournament reveal'
        if (pendingKnock(probe)) return 'a knock lands on the week after'
        if (pendingBirthday(probe) !== null) return 'a birthday lands on the week after'
        if (pendingLifeBeat(probe) !== null) return 'a blocking beat lands on the week after, and its card would cover hers'
        if (buildTourBriefing(probe) !== null) return 'the tour briefing would land on the week after'
        return null
      }
      return world.ending !== null
        ? `career ended (${world.ending.type}) before she came by`
        : `no small talk in ${SOFT_CAP_WEEK} weeks`
    },
  },
  {
    name: 'breakup',
    // ⭐⭐⭐ v75 T8 – THE WEEK BEFORE IT ENDS. See FIXTURE_NAMES in tools/e2e-fixtures-read.ts for why
    // the ending needed two fixtures of its own and why no existing career could hold either state.
    purpose:
      'A live attachment the parent was told about, one press from the end of it – the told-now card, and her Mood two rungs lower behind it.',
    background: 'middle',
    coachTier: 'middle',
    policy: PLAYER,
    // ⚠ NEVER REACHED BY THIS WALK: nobody can arrive before sixteen, the fork is at nineteen, and
    // `answerOpenQuestions` answers it on the way past years before an ending can be looked for. It is
    // `'continue'` because that is the one answer of the three that leaves a career still being
    // played, and this recipe walks for four more seasons after it.
    fork: 'continue',
    drive: (world, rng, recipe) => {
      while (world.week < ENDS_CAP_WEEK && world.ending === null) {
        stepCareerWeek(world, rng, recipe.policy, undefined, { drainKnocks: false })
        // ⚠ THE ARRIVAL CARD IS ANSWERED ON THE WAY PAST AND THAT IS THE POINT, NOT A COMPROMISE. The
        // bond-neutral drain answers `'met'` like every other recipe in this file – and a drained
        // `'met'` row is still a `'met'` row, which is exactly the receipt ruling A reads to decide
        // this ending is a told-NOW one. A recipe that skipped the drain would be hunting the other
        // fixture.
        answerOpenQuestions(world, recipe.fork)

        // ⭐ THE CHEAP GATE FIRST, AND IT IS THE ENGINE'S OWN «IS SOMEBODY THERE» (`activeEpisode`,
        // which `endsEligible` asks and nothing else). Most weeks of most careers fail it, so the
        // clone below is only paid for on the weeks that could possibly be the one.
        const live = activeEpisode(world)
        if (live === null) continue
        // ...AND HE HAS BEEN TOLD. `hasBeatFor`'s own note carries the whole of why this is the
        // receipt and never `knownWeek <= endedWeek`.
        if (!hasBeatFor(world, live.id, ['met'])) continue

        // ⭐⭐⭐ THE LOOK-AHEAD, AND IT RUNS BEFORE EVERY REJECTION CLAUSE BELOW – which is the one
        // structural difference from `soft`'s walk and it is deliberate. «Does the hazard fire next
        // week» is a 1.2%-a-week question, so it is the rare condition and it must be the one that
        // `continue`s; a clause that REJECTED the seed on a knock would otherwise throw away careers
        // for a reason that has nothing to do with the state being hunted. Once the ending IS coming,
        // every remaining clause rejects, on `unheard`'s stated grounds: a clause here survives the
        // next regeneration, a spec that steps around a bad seed survives only until the one after.
        //
        // ⚠ THE LOOK-AHEAD IS EXACT, NOT AN ESTIMATE – `sinking`'s, `unheard`'s and `soft`'s own
        // precedent. The clone carries `rngMain`, so resuming MAIN from it walks the sequence the
        // browser will walk and `tickWeek` is what the worker runs behind the week button. Nothing
        // about the fixture's own world is touched.
        const probe = structuredClone(world)
        tickWeek(probe, resumeMain(probe.rngMain))
        const raised = pendingLifeBeat(probe)
        if (raised === null || raised.kind !== 'ended' || raised.detail !== live.id) continue

        // ⚠⚠ NOTHING MAY BE STANDING IN FRONT OF THE WEEK BUTTON ON THE WEEK THIS BOOTS AT. The spec's
        // first act is to press it, so a career booting into somebody else's blocking card is a career
        // whose press never happens – and `advanceRefusal` is the engine's own answer to «may time
        // move», the same predicate `advanceWeeks` guards on.
        if (pendingKnock(world)) return 'boots holding a knock, and the spec presses the week button first'
        if (pendingBirthday(world) !== null) return 'boots holding a birthday, and the spec presses the week button first'
        if (world.pendingTournament) return 'boots into a tournament reveal, which holds the week back'
        // ⚠ AND THE BRIEFING, which is not in `blockingOverlay`'s list but is a blocking card all the
        // same – `unheard`'s and `soft`'s own clause, for the reason they both give.
        if (buildTourBriefing(world) !== null) return 'the tour briefing is owed and would land over the week'
        // ⚠ REACHABLE DESPITE THE DRAIN ABOVE, WHICH IS WHY IT IS HERE AND NOT ASSUMED AWAY:
        // `answerOpenQuestions` drains and THEN answers the fork, and answering the fork can raise
        // `'fork-counsel'` behind it (v74 T17, `unheard`'s own hard-won clause). That row would be the
        // card the browser boots into.
        if (pendingLifeBeat(world) !== null) return 'boots holding a blocking beat, whose card covers the week button'
        const refusal = advanceRefusal(world)
        if (refusal !== null) return `the week is stopped by '${refusal}' before the ending can be reached`

        // ⭐⭐⭐ AND HER MOOD HAS ROOM TO FALL, WHICH IS THE HALF A SPEC CANNOT HOPE FOR. `moodRung`'s
        // own note carries why this is asked of `toSnapshot` and why −1 is a rejection rather than a
        // fallback. The two reads bracket the press exactly as the browser's do: the parked week, and
        // the week the ending lands on with the card already answered – `answerLifeBeat` moves BOND
        // and never spirit (the brief's own red flag), so the second read is the shock and nothing
        // else.
        const moodBefore = moodRung(world)
        if (moodBefore < 0) return 'her Mood tile is speaking a body word, so a spirit rung cannot be compared'
        answerLifeBeat(probe, ENDS_ANSWER_ID)
        const moodAfter = moodRung(probe)
        if (moodAfter < 0) return 'her Mood tile turns to a body word on the week it ends, and the two ladders are not comparable'
        // ⚠ THE RUNGS RUN TOP-DOWN (`SPIRIT_BANDS`: glowing … heavy), so a DIP is a LARGER index.
        //
        // ⚠⚠ **TWO RUNGS AND NOT ONE, AND THE SECOND ONE WAS BOUGHT BY A MUTATION THAT CAME BACK
        // GREEN.** The obvious bar is `moodAfter <= moodBefore`, and e2e/breakup.spec.ts was written
        // against it – until the arm that drops the shock summand from `accrueSpirit` left the browser
        // spec PASSING. Measured on this very fixture with the summand gone: spirit 75 -> 72 (the
        // ATTACHMENT LIFT coming off, which happens on the same tick and is a different mechanism),
        // `DiaryFacts.moodWord` null because the BODY channel then wins the week, and KidScreen's
        // fallback printing «Steady» – which is on the spirit ladder too, by the owner's ruling that
        // «the neutral state is one state and gets one word». One shared word, two ladders, and a
        // one-rung «dip» that the shock had nothing to do with.
        //
        // So the bar is the SHOCK's own size rather than any movement at all: −22/−34 against a lift
        // worth 5 cannot be confused with it, and the two-rung floor is what a page that cannot see
        // `moodWord`'s nullability can still assert honestly. ⚠ IT IS A PROPERTY OF THE FIXTURE, which
        // is why it is enforced here: a career parked at `Dimmed` has only one rung left below it and
        // is rejected, however hard the shock hits.
        if (moodAfter - moodBefore < 2) return `her Mood does not drop TWO rungs when it ends (${MOOD_WORD[SPIRIT_BANDS[moodBefore]]} -> ${MOOD_WORD[SPIRIT_BANDS[moodAfter]]}) – one rung is reachable by the attachment lift alone`

        // ⚠⚠ AND ANSWERING HER LEAVES AN ORDINARY WEEK. The spec closes by pressing the week button a
        // second time and reading the next week off the screen, so a card standing behind hers, or a
        // tick that ends the career or opens a reveal, would replace the surface it is reading.
        const stillBlocked = advanceRefusal(probe)
        if (stillBlocked !== null) return `answering her leaves a '${stillBlocked}' standing in the week's way`
        tickWeek(probe, resumeMain(probe.rngMain))
        if (probe.ending !== null) return `the week after the ending ends the career (${probe.ending.type})`
        if (probe.pendingTournament) return 'the week after the ending opens a tournament reveal'
        if (pendingKnock(probe)) return 'a knock lands on the week after the ending'
        if (pendingBirthday(probe) !== null) return 'a birthday lands on the week after the ending'
        if (pendingLifeBeat(probe) !== null) return 'a blocking beat lands on the week after the ending'
        if (buildTourBriefing(probe) !== null) return 'the tour briefing would land on the week after the ending'
        return null
      }
      return world.ending !== null
        ? `career ended (${world.ending.type}) before anything of hers did`
        : `nothing she was told about ended in ${ENDS_CAP_WEEK} weeks`
    },
  },
  {
    name: 'belated',
    // ⭐⭐⭐ v75 T8 – THE OTHER REGISTER, AND THE ONE WITH NO BROWSER ANYWHERE IN THE SUITE UNTIL NOW.
    purpose:
      'An attachment that was over before he heard of it – one press from the told-late card, and no arrival card is ever raised for it.',
    background: 'middle',
    coachTier: 'middle',
    policy: PLAYER,
    // ⚠ NEVER REACHED BY THIS WALK EITHER – `breakup`'s own reason, one recipe up.
    fork: 'continue',
    drive: (world, rng, recipe) => {
      while (world.week < ENDS_CAP_WEEK && world.ending === null) {
        stepCareerWeek(world, rng, recipe.policy, undefined, { drainKnocks: false })
        answerOpenQuestions(world, recipe.fork)

        // ⭐⭐⭐ THE GATE, AND IT IS THE TOLD-LATE SCENE STATED IN THE SCHEMA'S OWN TERMS: a row that is
        // ALREADY OVER (`endedWeek`), whose news is owed NEXT WEEK (`knownWeek`), and which has never
        // produced a beat of either kind. `deliverKnownPartner` scans for exactly this row (ruling B)
        // and takes the told-late branch on it, so the next tick raises one `'ended'` card in its
        // told-late register and NO `'met'` beat, ever.
        //
        // ⚠ `=== world.week + 1` AND NOT `<= world.week`, deliberately: delivery is unconditional in
        // the tick, so a row already due would have been delivered on a tick that has already run. The
        // state this fixture is for is the week BEFORE the news, which is the only week from which a
        // browser can press the button and watch it arrive.
        const due = loveEpisodesOf(world).find(
          (episode) =>
            episode.endedWeek !== null &&
            episode.knownWeek === world.week + 1 &&
            !hasBeatFor(world, episode.id, ['met', 'ended']),
        )
        if (due === undefined) continue

        // The look-ahead, on `breakup`'s own terms and for its stated reasons.
        // ⭐⭐⭐ THE PROBE WALKS WHAT THE BROWSER WALKS, AND FOR THIS RECIPE THAT INCLUDES TWO DOORWAYS.
        //
        // ⚠⚠ THIS IS WHERE `belated` DEPARTS FROM `breakup`, AND THE DEPARTURE IS MEASURED RATHER THAN
        // CONVENIENT. `breakup` demands a career that boots with NOTHING in front of it, and can
        // afford to: its state turns up on ~40% of seeds, so the first one qualified. `belated`'s
        // turns up on 1.9% – MEASURED, 8 careers in 432 seeds – and of those eight, FOUR were thrown
        // away by clauses about things the suite already steps through: two behind an opening knock,
        // two behind an owed tour briefing. `e2e/journey.ts` has a helper for each
        // (`answerOpeningKnock`, `dismissTourBriefing`) and argues both at length – they are FIXTURE
        // STATE, not the thing any journey is testing, and `junior` and `pro` have booted behind a
        // knock since the corpus existed. Rejecting half the corpus's rarest state for a doorway the
        // spec walks through anyway is a clause buying nothing at a price nothing else here pays.
        //
        // ⚠ THE TWO ARE NOT THE SAME KIND OF DOORWAY, and only one of them costs the look-ahead a line.
        // Dismissing the BRIEFING writes a watermark to localStorage (`markSeen`, composables/
        // inboxCue.ts) and touches no world at all, so the walk below is unaffected by it. Answering a
        // KNOCK is an engine command that moves `bond` and the body – so it is replayed HERE, through
        // the same shared helper every other harness uses, which presses `'rest'` exactly as
        // `answerOpeningKnock` does. A look-ahead that skipped it would be measuring a different week
        // from the one the browser reaches, which is the whole thing these clones exist to prevent.
        const probe = structuredClone(world)
        drainKnock(probe)
        // ⚠ AND THE «MAY TIME MOVE» QUESTION IS ASKED **AFTER** THAT ANSWER, because that is when the
        // spec asks it. A career whose only refusal was the knock is a career the browser can press.
        const refusal = advanceRefusal(probe)
        if (refusal !== null) return `the week is stopped by '${refusal}' before the news can be reached`
        tickWeek(probe, resumeMain(probe.rngMain))
        const raised = pendingLifeBeat(probe)
        if (raised === null || raised.kind !== 'ended' || raised.detail !== due.id) continue
        // ⚠⚠ AND IT IS THE TOLD-LATE REGISTER, ASKED THE WAY THE ENGINE ASKS IT. `beatEndsRegister`
        // reads the `'met'` receipt and finds none; this is that same question from outside, and it is
        // ALSO the assertion that the brief's «no `'met'` beat fires for a finished episode» held on
        // this career rather than on a reading of the code.
        if (hasBeatFor(probe, due.id, ['met'])) return 'the delivery raised an arrival card for an episode that was already over'

        // THE THREE WITH NO DOORWAY, asked of the week this boots at. A birthday and a reveal both
        // OUTRANK her card (`blockingOverlay`, and `screenBusy` for the reveal – a life beat is not in
        // `INTERRUPTS`, so a takeover holds it back), and a blocking beat already standing would be a
        // card the spec knows nothing about. None of the three has a step-through in e2e/journey.ts,
        // and none should: they are questions, not doorways.
        if (pendingBirthday(world) !== null) return 'boots holding a birthday, which outranks her card in the queue'
        if (world.pendingTournament) return 'boots into a tournament reveal, which holds her card back'
        if (pendingLifeBeat(world) !== null) return 'boots holding a blocking beat, whose card covers the week button'

        // ⚠⚠ NO MOOD ARM HERE, AND ITS ABSENCE IS THE MECHANIC RATHER THAN AN OMISSION. The shock is
        // stamped and spent at `endedWeek` (`rollEnds` -> `accrueSpirit`, ruling C), which on this path
        // is seasons behind the week the parent hears of it. A told-late card over a falling Mood
        // would be the sim claiming she takes the news when HE does, and she does not.
        answerLifeBeat(probe, ENDS_ANSWER_ID)
        // ⚠⚠ THE CLAUSE THAT DOES MOST OF THE REJECTING HERE IS THIS ONE, AND IT READS MILDER THAN IT
        // IS. `advanceRefusal` returns `'tournament'` for exactly one state – `world.pendingTournament`
        // – and a pending reveal OUTRANKS a life beat in `blockingOverlay`, so a career in it does not
        // merely have a week it cannot advance: the card the browser would meet on this week is the
        // DRAW, not hers, and the spec's first assertion would be about a dialog it knows nothing
        // about. MEASURED: of the four careers in the first 200 seeds that reached the told-late state
        // at all, THREE died on this line and one on the knock clause above – which is why
        // `DEFAULT_BUDGET` moved rather than the recipe. Reveals are dense in a professional season,
        // and a told-late episode needs an arrival, so the two cluster in the same years.
        const stillBlocked = advanceRefusal(probe)
        if (stillBlocked !== null) return `answering her leaves a '${stillBlocked}' standing in the week's way`
        tickWeek(probe, resumeMain(probe.rngMain))
        if (probe.ending !== null) return `the week after the news ends the career (${probe.ending.type})`
        if (probe.pendingTournament) return 'the week after the news opens a tournament reveal'
        if (pendingKnock(probe)) return 'a knock lands on the week after the news'
        if (pendingBirthday(probe) !== null) return 'a birthday lands on the week after the news'
        if (pendingLifeBeat(probe) !== null) return 'a blocking beat lands on the week after the news'
        if (buildTourBriefing(probe) !== null) return 'the tour briefing would land on the week after the news'
        return null
      }
      return world.ending !== null
        ? `career ended (${world.ending.type}) before anything of hers did`
        : `nothing ended behind his back in ${ENDS_CAP_WEEK} weeks`
    },
  },
]

// --- the search -----------------------------------------------------------------------------------

/** ⚠ 24 -> 200 AFTER THE JUNIOR-LADDER WAVE (16.08), AND THE NUMBER IS MEASURED RATHER THAN ROUND.
 *
 *  `junior` now carries three requirements at once – a ranking, an open knock and an entry for the
 *  week ahead – and the wave made the conjunction rare: the seed that satisfied all three was the
 *  **62nd** tried, against the 20th before P1 and the 19th before that. At the old budget of 24 this
 *  regeneration failed outright, which is the tool working correctly and reporting an honest state
 *  ("never hand-edit a world to make the state exist") rather than a bug.
 *
 *  THE COST OF THE HIGHER CEILING IS ZERO WHEN IT IS NOT NEEDED – the loop stops at the first seed
 *  that qualifies, so every other fixture still finishes on its first – and the cost of the LOWER one
 *  was a red gate nobody could act on without re-deriving this paragraph. If a future wave pushes the
 *  search past this, the message says so by name and the fix is a recipe decision, not a bigger
 *  number: three requirements on one fixture is already the most any of them carries.
 *
 *  ⭐⭐⭐ 200 -> 900 FOR v75 T8's `belated`, AND THE PARAGRAPH ABOVE PREDICTED THE WRONG HALF OF ITS OWN
 *  FUTURE. It said a search pushing past 200 would be «a recipe decision, not a bigger number», on the
 *  premise that the binding constraint is ever CONJUNCTION – three requirements on one fixture. It is
 *  not, here. `belated`'s state is a single fact that the model makes RARE, and no recipe decision can
 *  make a rare fact common without poking a world into shape, which is the one thing this file may
 *  never do.
 *
 *  ⚠⚠ THE NUMBER IS MEASURED AND THE MEASUREMENT IS THIS. A throw-away census walked **40 careers** on
 *  this recipe's own settings (middle / middle / PLAYER, bond-neutral answers, eight seasons) and
 *  counted every episode they produced:
 *
 *      1.70 attachments per career          – nobody may arrive before sixteen, so 260 eligible weeks
 *      1.47% of them ended before `knownWeek` (1 of 68)
 *      lag: mean 1.56 weeks, > 0 on 54% of episodes, `wants` 37 open / 31 private
 *
 *  So a career holds the told-late state with p ≈ 1.70 x 1.47% ≈ **2.5%**. ⭐⭐ AND THE SEARCH THEN
 *  MEASURED THE REST OF IT, WHICH IS WORSE THAN THE ESTIMATE AND FOR A REASON WORTH KEEPING: the
 *  accepted seed was **the 473rd**, and of the eight careers before it that DID hold the state, EVERY
 *  ONE was thrown out by a TOURNAMENT REVEAL on or immediately after the delivery tick. That is not
 *  bad luck – a reveal is a takeover (`screenBusy`, composables/blockingOverlay.ts) and a life beat is
 *  not in `INTERRUPTS`, so her card is HELD behind it; and the told-late scene needs an arrival, which
 *  needs sixteen, which puts it in the years she is entered in something most weeks. The two cluster
 *  by construction. Measured end to end: **1 seed in 473, 951 s of walking.**
 *
 *  ⚠ 200 WOULD HAVE FAILED OUTRIGHT – it did, twice, and the tool said so in its own words («no seed
 *  in 200 reached the state»), which is the honest state this file is built to report. 900 carries the
 *  measured rate with room; a future wave that finds even this too tight should move the CLAUSES it
 *  can honestly move before it moves the number again – `belated`'s own recipe already walks through
 *  the knock and the briefing for exactly that reason, and the reveal is the one that cannot.
 *
 *  ⚠ WHY THE LAG IS THE SCARCE PART, since a reader will reach for the hazard first: an attachment can
 *  only end behind the parent's back INSIDE its disclosure lag, and `bondShave` divides that lag by 2
 *  at `steady` (by 3 at `close`) – and a walked career sits at bond 70, which is `steady`. Open girls
 *  draw `0` outright 70% of the time. So the window the end hazard has to land in is usually one week
 *  and often none at all, which is the design working (an open girl's parent «usually hears at once»)
 *  and not a number to tune.
 *
 *  ⚠ AND THE COST IS NOT ZERO THIS TIME, WHICH THE SENTENCE ABOVE COULD NO LONGER CLAIM. The other
 *  nine still finish on their first or twentieth seed and pay nothing. `belated` cost **473 seeds and
 *  ~16 minutes**, and a seed here is a whole eight-season walk. `--only` keeps that off every day's
 *  work; a schema bump pays it once. A cheaper `belated` would have to be a LESS TRUE one, and the
 *  corpus's founding rule prices that trade for us. */
const DEFAULT_BUDGET = 900

interface Generated {
  entry: FixtureEntry
  bytes: Uint8Array
}

async function generate(recipe: Recipe, budget: number): Promise<Generated> {
  for (let i = 0; i < budget; i++) {
    // Seeds are ENUMERATED, not rolled: the search is a deterministic walk, so a regeneration finds
    // the same career and no randomness of this tool's own can perturb anything.
    const seed = `e2e-${recipe.name}-${i}`
    const { world, rng } = openFixtureCareer(recipe.name, seed, recipe.background, recipe.coachTier, recipe.policy)
    const rejected = recipe.drive(world, rng, recipe)
    if (rejected !== null) {
      // A refusal prints WHAT THE CAREER ACTUALLY BECAME, not just which clause said no. The first
      // run of the `pro` recipe rejected 24 careers on "unranked internationally" and the line said
      // nothing about the fact that every one of them was alive, solvent and holding a professional
      // ranking – the criterion was reading the junior table at twenty-two. A search that cannot be
      // debugged from its own output is a search someone will "fix" by loosening it blindly.
      console.log(`    ${seed}: ${rejected}  [${summarise(world)}]`)
      continue
    }

    const bytes = await encodeExportFile(world)
    // The product's own reader, before anything is written: a fixture that cannot be imported is
    // not a fixture. This also proves the facts survive the encode/decode round trip.
    const readBack = await decodeExportFile(bytes)
    const facts = factsOf(world)
    const readBackFacts = factsOf(readBack)
    if (JSON.stringify(facts) !== JSON.stringify(readBackFacts)) {
      throw new Error(`${recipe.name}: the encoded save does not read back as the world it came from`)
    }

    const digest = await sha256(bytes)
    return {
      bytes,
      entry: {
        name: recipe.name,
        file: `${recipe.name}.tsave`,
        purpose: recipe.purpose,
        seed,
        careerId: world.careerId,
        slot: slotFor(recipe.name),
        targetWeek: world.week,
        schemaVersion: world.schemaVersion,
        background: recipe.background,
        coachTier: recipe.coachTier,
        policy: recipe.policy.id,
        profile: {
          kidName: world.profile.kidName,
          kidLastName: world.profile.kidLastName,
          country: world.profile.country,
        },
        bytes: bytes.byteLength,
        payloadBytes: bytes.byteLength - ENVELOPE_HEADER_BYTES,
        sha256: [...digest].map((b) => b.toString(16).padStart(2, '0')).join(''),
        seedsTried: i + 1,
        facts,
      },
    }
  }
  throw new Error(
    `${recipe.name}: no seed in ${budget} reached the state. Raise --budget, or say so in the doc ` +
      `and change the recipe – never hand-edit a world to make the state exist.`,
  )
}

function arg(name: string, fallback: string): string {
  const i = process.argv.indexOf(`--${name}`)
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback
}

function money(cents: number): string {
  return `${cents < 0 ? '-' : ''}$${Math.abs(Math.round(cents / 100)).toLocaleString('en-US')}`
}

/** The one-line state of a career, for the search log. Three point columns because there are three
 *  tables and they are three different currencies (season/types.ts LadderTrack). */
function summarise(world: WorldState): string {
  const f = factsOf(world)
  return (
    `w${f.week} age ${f.ageYears} ${money(f.fundsCents)} rank ${f.kidRank} ` +
    `pts dom/itf/wta ${f.domesticPoints}/${f.itfPoints}/${f.wtaPoints} ` +
    `letters ${f.openKitLetters}${f.hasActiveKitDeal ? ' deal' : ''}${f.endingType ? ` ${f.endingType}` : ''}`
  )
}

export async function main(): Promise<void> {
  const only = arg('only', '')
  const budget = Number(arg('budget', String(DEFAULT_BUDGET)))
  const recipes = only ? RECIPES.filter((r) => r.name === only) : RECIPES
  if (recipes.length === 0) throw new Error(`--only ${only}: no such fixture (${FIXTURE_NAMES.join(', ')})`)

  console.log('')
  console.log(`E2E FIXTURES – schema v${SAVE_SCHEMA_VERSION}, ${recipes.length} to build, budget ${budget} seeds each`)
  console.log('')

  mkdirSync(FIXTURE_DIR, { recursive: true })
  // A partial run keeps the fixtures it is not rebuilding, so `--only pro` cannot silently drop the
  // other six out of the manifest.
  const kept = only && readdirSync(FIXTURE_DIR).includes('manifest.json') ? loadManifest().fixtures : []
  const entries: FixtureEntry[] = kept.filter((e) => !recipes.some((r) => r.name === e.name))

  for (const recipe of recipes) {
    const at = Date.now()
    process.stdout.write(`  ${recipe.name.padEnd(7)} `)
    console.log('searching…')
    const { entry, bytes } = await generate(recipe, budget)
    writeFileSync(`${FIXTURE_DIR}${entry.file}`, bytes)
    entries.push(entry)
    const f = entry.facts
    console.log(
      `    -> ${entry.seed} · week ${f.week} · age ${f.ageYears} · ${money(f.fundsCents)} · rank ${f.kidRank} · ` +
        `${(bytes.byteLength / 1024).toFixed(1)} KiB · ${entry.seedsTried} seed(s) · ${((Date.now() - at) / 1000).toFixed(0)}s`,
    )
  }

  entries.sort((a, b) => FIXTURE_NAMES.indexOf(a.name) - FIXTURE_NAMES.indexOf(b.name))
  const manifest: FixtureManifest = {
    generatedBy: 'tools/e2e-fixtures.ts',
    command: 'npm run e2e:fixtures',
    schemaVersion: SAVE_SCHEMA_VERSION,
    fixtures: entries,
  }
  writeFileSync(MANIFEST_FILE, `${JSON.stringify(manifest, null, 2)}\n`)

  const total = entries.reduce((sum, e) => sum + e.bytes, 0)
  console.log('')
  console.log(`  manifest: ${entries.length} fixtures, ${(total / 1024).toFixed(1)} KiB on disk`)
  console.log('')
  // A sanity line rather than a decoration: the starting funds are a per-background constant, so a
  // week-0 fixture that does not hold it means the recipe wandered off its own preset.
  const fresh = entries.find((e) => e.name === 'fresh')
  if (fresh && fresh.facts.fundsCents !== STARTING_FUNDS_CENTS[fresh.background]) {
    throw new Error('fresh: week-0 funds are not the background\'s starting funds')
  }
}

// THE SAME GUARD THE BENCHES CARRY, AND FOR THE SAME MEASURED REASON (see the long note at the foot
// of tools/econ-bench.ts): this runner's `vite-node` STRIPS THE ENTRY FILE from `process.argv`, so a
// naive `argv[1]` check is false on every invocation and the tool exits 0 having done nothing. npm
// still puts the whole script body in `npm_lifecycle_script`, so the name is looked for in both
// places; `TB_FIXTURES_RUN=1` is the override for a bare `npx vite-node tools/e2e-fixtures.ts`.
// The VITEST arm is what keeps the rot alarm's import from launching a multi-minute seed search.
const NAMED_ON_THE_COMMAND_LINE =
  process.argv.some((a) => a.includes('e2e-fixtures')) ||
  (process.env.npm_lifecycle_script ?? '').includes('e2e-fixtures') ||
  process.env.TB_FIXTURES_RUN === '1'
if (!process.env.VITEST && NAMED_ON_THE_COMMAND_LINE) void main()
