/**
 * THE E2E FIXTURE ENGINE – career saves for the Playwright layer, generated by playing.
 *
 * Run:  npm run e2e:fixtures                 (all five, ~4 s, byte-identical every time)
 *       npm run e2e:fixtures -- --only pro   (one of them; the other four keep their manifest rows)
 *       npm run e2e:fixtures -- --budget 40  (how many seeds a search may try before it gives up)
 *
 * WHY IT EXISTS. A browser test that wants a career at week 412 cannot click there – it is eight
 * seasons of decisions – and fast-forwarding there costs minutes per test and couples every test to
 * the balance model. So the state is written into IndexedDB before the app boots, and this file
 * makes the bytes. Setup drops from minutes to milliseconds, which is what makes the whole e2e
 * layer affordable (docs/plans/playwright.md §3).
 *
 * ⚠ WHAT THIS FILE IS NOT ALLOWED TO DO, and it is the rule the fixtures live or die by:
 * IT NEVER HAND-EDITS A WORLD. Every state below is REACHED by playing – the engine's own
 * `createWorld`, the shared career loop from tools/econ-bench.ts, and the engine's own answers to
 * the questions the engine raises (`answerFork`). Where a state is rare, the generator SEARCHES
 * SEEDS until a career genuinely arrives at it and records the seed that did. A world poked into
 * shape is a fixture that could not have happened in play, and a test standing on one tests nothing.
 * The one exception is `careerId`, which the engine does not own at all: the worker mints it from
 * `Date.now()` outside the deterministic engine (`makeCareerId`), so the fixtures pin a stable one.
 *
 * ⚠ THE BYTES ARE THE PRODUCT'S OWN. `encodeExportFile` writes them and `decodeExportFile` reads
 * them back before anything is committed to disk – the versioned envelope, the gzip payload and the
 * SHA-256 that guards it. Nothing here re-implements the format, so a fixture cannot disagree with
 * what the app reads. The same file works through the app's "Import from file" door and, sliced at
 * the header, as the IndexedDB record the harness seeds (see `splitEnvelope`).
 *
 * ⚠ ZERO NEW RANDOMNESS ON MAIN. The generator takes no draw of its own: it hands the engine the
 * world's OWN persisted MAIN position (`resumeMain(world.rngMain)` – the serializer rule from
 * tools/demo-save.ts, which a raw `rngFromSeed` tap would break by shipping a week-412 career whose
 * saved stream position says zero), and the only other randomness it touches is the engine's own
 * purpose-scoped `seed:surname` sub-stream for the kid's family name. The frozen MAIN capture
 * cannot see this file.
 *
 * ⚠ THE OWNER'S OWN SAVE IS NEVER A FIXTURE. Generated careers only – it may be read locally for
 * diagnosis and is never committed, derived from or copied here.
 *
 * NOT THE GOLDEN-SAVE CORPUS. `tests/fixtures/saves/vN.json` is one raw world per schema version and
 * exists to prove MIGRATIONS work; these are five playable STATES at the current version and exist
 * to give a browser somewhere to start. See docs/plans/e2e-fixtures.md §"Two corpora".
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import {
  answerFork,
  answerRetirement,
  autoEndingViewOf,
  createWorld,
  kidAgeYears,
  kidPoints,
  seasonIndexOf,
  SAVE_SCHEMA_VERSION,
  STARTING_FUNDS_CENTS,
  type WorldState,
} from '../src/engine/world'
import { resumeMain, rngFromSeed, pickInt, type Rng } from '../src/engine/rng'
import { decodeExportFile, encodeExportFile, sha256 } from '../src/engine/saveCodec'
import { debtWeeks, ENDINGS } from '../src/engine/ending'
import { activeKitDeal, isSponsorWindowWeek } from '../src/engine/offers'
import { FIRST_NAMES, pickSurname } from '../src/engine/season/cohort'
import { WEEKS_PER_YEAR } from '../src/engine/season/calendar'
import { DEFAULT_PROFILE, type CoachTier, type FamilyBackground, type PlayerProfile } from '../src/shared/protocol'
import { POLICIES, stepCareerWeek, type Policy } from './econ-bench'

// --- where they live ------------------------------------------------------------------------------

export const FIXTURE_DIR = fileURLToPath(new URL('../e2e/fixtures/', import.meta.url))
export const MANIFEST_FILE = `${FIXTURE_DIR}manifest.json`

export const FIXTURE_NAMES = ['fresh', 'junior', 'pro', 'broke', 'ending'] as const
export type FixtureName = (typeof FIXTURE_NAMES)[number]

/** The header layout `encodeExportFile` writes: MAGIC(8) | schemaVersion u32 BE | sha256(32) | gzip.
 *  Named here so the harness's IndexedDB seeding and the rot alarm slice it in one place. */
export const ENVELOPE_HEADER_BYTES = 44

// --- what a test is told about a fixture ----------------------------------------------------------

/** The facts a spec may stand on. Every one of them is RE-DERIVED from the loaded world by the rot
 *  alarm (tests/e2e-fixtures.test.ts) and compared to what the manifest claims, so a fixture whose
 *  numbers have drifted out from under it fails on the PR gate rather than in a browser. */
export interface FixtureFacts {
  week: number
  seasonIndex: number
  ageYears: number
  fundsCents: number
  kidRank: number
  /** ranked at all – the engine's own test, `points > 0`, not the length of a results list.
   *  ⚠ THREE TABLES, THREE CURRENCIES (season/types.ts): National, junior International and
   *  Professional. A career reads as unranked on two of them for most of its life – the junior
   *  columns empty out as she ages past the J rungs – so a spec has to name the table it means. */
  rankedDomestic: boolean
  rankedItf: boolean
  rankedWta: boolean
  domesticPoints: number
  itfPoints: number
  wtaPoints: number
  seasonsPlayed: number
  resultRows: number
  feedEvents: number
  financeWeeks: number
  cohortSize: number
  endingType: string | null
  /** consecutive weeks below zero, counting this one – 0 when solvent */
  debtWeeks: number
  inSponsorWindow: boolean
  openKitLetters: number
  hasActiveKitDeal: boolean
  rngMain: { s: number; n: number }
}

export interface FixtureEntry {
  name: FixtureName
  file: string
  /** one sentence: which seam a spec would reach for this fixture to test */
  purpose: string
  seed: string
  careerId: string
  /** the IndexedDB slot the harness should write it to (src/db/saves.ts naming) */
  slot: string
  /** the week the recipe aimed at – for the searched fixtures, the week it was FOUND at */
  targetWeek: number
  schemaVersion: number
  background: FamilyBackground
  coachTier: CoachTier
  policy: Policy['id']
  profile: { kidName: string; kidLastName: string; country: string }
  bytes: number
  payloadBytes: number
  /** SHA-256 of the WHOLE envelope, hex. The envelope's own checksum covers the payload; this one
   *  covers the header too, so a truncated or re-headered file is caught before it is decoded. */
  sha256: string
  /** how many seeds the search tried before this one was accepted (1 = the first) */
  seedsTried: number
  facts: FixtureFacts
}

export interface FixtureManifest {
  generatedBy: string
  command: string
  /** the schema every fixture in this manifest was written at */
  schemaVersion: number
  fixtures: FixtureEntry[]
}

// --- reading (the rot alarm and the Playwright harness both come through here) --------------------

export function loadManifest(): FixtureManifest {
  return JSON.parse(readFileSync(MANIFEST_FILE, 'utf8')) as FixtureManifest
}

export function readFixtureBytes(file: string): Uint8Array {
  return new Uint8Array(readFileSync(`${FIXTURE_DIR}${file}`))
}

/**
 * The export envelope, cut into the two fields an IndexedDB save record holds.
 *
 * ⚠ THIS IS A SLICE, NOT A RE-ENCODE. `compressWorld` produced exactly these bytes and
 * `decompressWorld` verifies the checksum against them on read, so a record built this way is
 * byte-identical to one the app wrote itself. The alternative – decode the file and re-compress –
 * would put a second gzip implementation between the fixture and the product.
 */
export function splitEnvelope(bytes: Uint8Array): {
  schemaVersion: number
  checksum: Uint8Array
  payload: Uint8Array
} {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength)
  return {
    schemaVersion: view.getUint32(8),
    checksum: bytes.subarray(12, ENVELOPE_HEADER_BYTES),
    payload: bytes.subarray(ENVELOPE_HEADER_BYTES),
  }
}

/** Everything a spec asserts on, read off a world. The single definition – the generator writes the
 *  manifest with it and the rot alarm re-derives with it, so the two cannot drift apart. */
export function factsOf(world: WorldState): FixtureFacts {
  const domesticPoints = kidPoints(world, 'domestic')
  const itfPoints = kidPoints(world, 'itf')
  const wtaPoints = kidPoints(world, 'wta')
  return {
    week: world.week,
    seasonIndex: seasonIndexOf(world.week),
    ageYears: kidAgeYears(world.week, world.profile.birthMonth),
    fundsCents: world.fundsCents,
    kidRank: world.kidRank,
    rankedDomestic: domesticPoints > 0,
    rankedItf: itfPoints > 0,
    rankedWta: wtaPoints > 0,
    domesticPoints,
    itfPoints,
    wtaPoints,
    seasonsPlayed: world.seasonHistory.length,
    resultRows: world.results.length,
    feedEvents: world.events.length,
    financeWeeks: world.financeWeeks.length,
    cohortSize: world.cohort.length,
    endingType: world.ending ? world.ending.type : null,
    debtWeeks: debtWeeks(autoEndingViewOf(world)),
    inSponsorWindow: isSponsorWindowWeek(world.week),
    openKitLetters: world.offers.filter((o) => o.kind === 'kit' && o.state === 'open').length,
    hasActiveKitDeal: activeKitDeal(world.offers, world.week) !== null,
    rngMain: { s: world.rngMain.s, n: world.rngMain.n },
  }
}

// --- generation -----------------------------------------------------------------------------------

/** A career the fixtures can start: the engine's own `createWorld`, plus the two things the engine
 *  deliberately does not own – a stable careerId (the worker mints one from `Date.now()`) and a name
 *  drawn from the shipped pools, never invented here.
 *
 *  ⚠ `resumeMain(world.rngMain)`, NOT `rngFromSeed(world.seed)`. This file SERIALIZES, and the two
 *  differ exactly there: both produce the same draws, but only the resumed generator writes the
 *  position back onto the world, so the exported career carries a TRUE `rngMain`. A raw tap would
 *  ship a week-412 save claiming zero draws spent, and the app would replay them on load. The same
 *  ruling is written out at length in tools/demo-save.ts; the benches, which never serialize, keep
 *  their raw taps. */
function openFixtureCareer(
  name: FixtureName,
  seed: string,
  background: FamilyBackground,
  coachTier: CoachTier,
  policy: Policy,
): { world: WorldState; rng: Rng } {
  // Her name comes out of the engine's own pools through a purpose-scoped sub-stream – the same
  // door onboarding's 🎲 uses. Nothing here may invent a surname: the pools are curated so that no
  // real player's name is constructible (see the SURNAMES note in season/cohort.ts), and a fixture
  // that made up its own would quietly leave that guarantee behind.
  const nameRng = rngFromSeed(`${seed}:e2e-given-name`)
  const profile: PlayerProfile = {
    ...DEFAULT_PROFILE,
    kidName: FIRST_NAMES[pickInt(nameRng, 0, FIRST_NAMES.length - 1)],
    kidLastName: pickSurname(seed),
    background,
    coachTier,
  }
  const world = createWorld(seed, profile, careerIdFor(name))
  world.coachOnEventWeeks = policy.coachOnEventWeeks
  return { world, rng: resumeMain(world.rngMain) }
}

export function careerIdFor(name: FixtureName): string {
  return `c-e2e-${name}`
}

export function slotFor(name: FixtureName): string {
  return `auto:${careerIdFor(name)}:a`
}

/** Answer whatever the engine has asked, the way tools/endings-bench.ts does – the fork at nineteen
 *  and the retirement offer are QUESTIONS, and a career that never answers them stops there.
 *  `fork` is the recipe's stance; the retirement offer cannot fire before 29 and is handled for
 *  completeness (refuse until the game stops asking, which keeps a career playing). */
function answerOpenQuestions(world: WorldState, fork: 'continue' | 'college' | 'stop'): void {
  if (world.fork !== null && world.fork.answer === null) answerFork(world, fork)
  if (world.retirementOffer !== null) answerRetirement(world, world.retirementOffer.final)
}

interface Recipe {
  name: FixtureName
  purpose: string
  background: FamilyBackground
  coachTier: CoachTier
  policy: Policy
  fork: 'continue' | 'college' | 'stop'
  /** walk the career; return the reason it was rejected, or null when this seed is the fixture */
  drive: (world: WorldState, rng: Rng, recipe: Recipe) => string | null
}

const GRINDER = POLICIES[0]
const PLAYER = POLICIES[1]

/** Play forward to `until`, answering every question on the way. Stops early if the career ends. */
function playTo(world: WorldState, rng: Rng, recipe: Recipe, until: number): void {
  while (world.week < until && world.ending === null) {
    stepCareerWeek(world, rng, recipe.policy)
    answerOpenQuestions(world, recipe.fork)
  }
}

/** ~week 412 – old enough that the ledgers are full, and week 412 % 52 = 48 puts her inside the
 *  five-week sponsor window by construction. */
const PRO_WEEK = 412
/** ~week 120 – the middle of her third season, by which a junior who is going to be ranked is. */
const JUNIOR_WEEK = 120
/** One week short of the latch. `bankruptcyDue` fires at ENDINGS.bankruptcyGraceWeeks consecutive
 *  weeks under water, and a spell reaches 12 only by passing through 11 – so this is the last week
 *  the family is still standing on the wrong side of the money, which is the state the warning
 *  phase exists for. */
const BROKE_DEBT_WEEKS = ENDINGS.bankruptcyGraceWeeks - 1
/** The fork is her nineteenth birthday week – five seasons and a bit. The cap is generous so a late
 *  birthday still lands inside it. */
const FORK_CAP_WEEK = 6 * WEEKS_PER_YEAR

const RECIPES: Recipe[] = [
  {
    name: 'fresh',
    purpose: 'A career the week it was created – the boot path, onboarding and the empty screens.',
    background: 'middle',
    coachTier: 'middle',
    policy: PLAYER,
    fork: 'continue',
    // Nothing to search: week 0 IS createWorld's output, and it is a real saved state because the
    // worker adopts an autosave the moment a career is made.
    drive: (world) => (world.week === 0 && world.ending === null ? null : 'not a week-0 world'),
  },
  {
    name: 'junior',
    purpose: 'First ranking earned – the junior ladder, the standings, a feed with something in it.',
    background: 'middle',
    coachTier: 'middle',
    policy: PLAYER,
    fork: 'continue',
    drive: (world, rng, recipe) => {
      playTo(world, rng, recipe, JUNIOR_WEEK)
      if (world.ending !== null) return `career ended (${world.ending.type}) before week ${JUNIOR_WEEK}`
      if (kidPoints(world, 'domestic') <= 0) return 'never earned a domestic ranking'
      if (world.seasonHistory.length < 2) return 'fewer than two seasons behind her'
      return null
    },
  },
  {
    name: 'pro',
    purpose: 'Eight seasons in, inside the sponsor window, ledgers full – the heavy-state screens.',
    background: 'middle',
    coachTier: 'middle',
    policy: PLAYER,
    fork: 'continue',
    drive: (world, rng, recipe) => {
      playTo(world, rng, recipe, PRO_WEEK)
      if (world.ending !== null) return `career ended (${world.ending.type}) before week ${PRO_WEEK}`
      if (world.week !== PRO_WEEK) return `stalled at week ${world.week}`
      if (!isSponsorWindowWeek(world.week)) return 'not inside the sponsor window'
      // ⚠ THE PROFESSIONAL TABLE, NOT THE JUNIOR ONE. At twenty-two her ITF (junior) points are
      // long gone – the J rungs cap at 18 and the tables are a rolling 52 weeks – so asking for
      // `itf` points here rejects every career that ever grew up. Three tables, three currencies.
      if (kidPoints(world, 'wta') <= 0) return 'unranked professionally'
      if (world.financeWeeks.length === 0) return 'no finance ledger'
      // The sponsor spec needs paper on the table: either a letter she can open and sign, or a deal
      // already running that the money screen can show.
      const openLetters = world.offers.filter((o) => o.kind === 'kit' && o.state === 'open').length
      if (openLetters === 0 && activeKitDeal(world.offers, world.week) === null) return 'no kit letter and no live deal'
      return null
    },
  },
  {
    name: 'broke',
    // The reckless arm on the tightest corridor – the cell the econ bench measures going under.
    purpose: 'Eleven weeks under water, one week short of the bankruptcy latch – the warning phase.',
    background: 'working',
    coachTier: 'middle',
    policy: GRINDER,
    fork: 'continue',
    drive: (world, rng, recipe) => {
      // Walk week by week and stop the moment the spell is one week short of the latch. Every spell
      // that ever reaches the grace window passes through this week, so the state is found rather
      // than constructed – and stopping here leaves the career still alive and still refusable.
      while (world.week < FORK_CAP_WEEK && world.ending === null) {
        stepCareerWeek(world, rng, recipe.policy)
        answerOpenQuestions(world, recipe.fork)
        if (debtWeeks(autoEndingViewOf(world)) === BROKE_DEBT_WEEKS) {
          return null
        }
      }
      return world.ending !== null
        ? `career ended (${world.ending.type}) without a ${BROKE_DEBT_WEEKS}-week spell`
        : 'never spent that long under water'
    },
  },
  {
    name: 'ending',
    purpose: 'Past the fork at nineteen, racket down – the epilogue, the album and a read-only career.',
    background: 'middle',
    coachTier: 'middle',
    policy: PLAYER,
    fork: 'stop',
    drive: (world, rng, recipe) => {
      // The fork is a QUESTION the engine raises on her nineteenth birthday week, and 'stop' is one
      // of the three answers a player can tap. Answering it is play; nothing is written by hand.
      playTo(world, rng, recipe, FORK_CAP_WEEK)
      if (world.ending === null) return 'the fork never came'
      if (world.ending.type !== 'stopped') return `ended as ${world.ending.type}, not at the fork`
      return null
    },
  },
]

// --- the search -----------------------------------------------------------------------------------

const DEFAULT_BUDGET = 24

interface Generated {
  entry: FixtureEntry
  bytes: Uint8Array
}

async function generate(recipe: Recipe, budget: number): Promise<Generated> {
  for (let i = 0; i < budget; i++) {
    // Seeds are ENUMERATED, not rolled: the search is a deterministic walk, so a regeneration finds
    // the same career and no randomness of this tool's own can perturb anything.
    const seed = `e2e-${recipe.name}-${i}`
    const { world, rng } = openFixtureCareer(recipe.name, seed, recipe.background, recipe.coachTier, recipe.policy)
    const rejected = recipe.drive(world, rng, recipe)
    if (rejected !== null) {
      // A refusal prints WHAT THE CAREER ACTUALLY BECAME, not just which clause said no. The first
      // run of the `pro` recipe rejected 24 careers on "unranked internationally" and the line said
      // nothing about the fact that every one of them was alive, solvent and holding a professional
      // ranking – the criterion was reading the junior table at twenty-two. A search that cannot be
      // debugged from its own output is a search someone will "fix" by loosening it blindly.
      console.log(`    ${seed}: ${rejected}  [${summarise(world)}]`)
      continue
    }

    const bytes = await encodeExportFile(world)
    // The product's own reader, before anything is written: a fixture that cannot be imported is
    // not a fixture. This also proves the facts survive the encode/decode round trip.
    const readBack = await decodeExportFile(bytes)
    const facts = factsOf(world)
    const readBackFacts = factsOf(readBack)
    if (JSON.stringify(facts) !== JSON.stringify(readBackFacts)) {
      throw new Error(`${recipe.name}: the encoded save does not read back as the world it came from`)
    }

    const digest = await sha256(bytes)
    return {
      bytes,
      entry: {
        name: recipe.name,
        file: `${recipe.name}.tsave`,
        purpose: recipe.purpose,
        seed,
        careerId: world.careerId,
        slot: slotFor(recipe.name),
        targetWeek: world.week,
        schemaVersion: world.schemaVersion,
        background: recipe.background,
        coachTier: recipe.coachTier,
        policy: recipe.policy.id,
        profile: {
          kidName: world.profile.kidName,
          kidLastName: world.profile.kidLastName,
          country: world.profile.country,
        },
        bytes: bytes.byteLength,
        payloadBytes: bytes.byteLength - ENVELOPE_HEADER_BYTES,
        sha256: [...digest].map((b) => b.toString(16).padStart(2, '0')).join(''),
        seedsTried: i + 1,
        facts,
      },
    }
  }
  throw new Error(
    `${recipe.name}: no seed in ${budget} reached the state. Raise --budget, or say so in the doc ` +
      `and change the recipe – never hand-edit a world to make the state exist.`,
  )
}

function arg(name: string, fallback: string): string {
  const i = process.argv.indexOf(`--${name}`)
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback
}

function money(cents: number): string {
  return `${cents < 0 ? '-' : ''}$${Math.abs(Math.round(cents / 100)).toLocaleString('en-US')}`
}

/** The one-line state of a career, for the search log. Three point columns because there are three
 *  tables and they are three different currencies (season/types.ts LadderTrack). */
function summarise(world: WorldState): string {
  const f = factsOf(world)
  return (
    `w${f.week} age ${f.ageYears} ${money(f.fundsCents)} rank ${f.kidRank} ` +
    `pts dom/itf/wta ${f.domesticPoints}/${f.itfPoints}/${f.wtaPoints} ` +
    `letters ${f.openKitLetters}${f.hasActiveKitDeal ? ' deal' : ''}${f.endingType ? ` ${f.endingType}` : ''}`
  )
}

export async function main(): Promise<void> {
  const only = arg('only', '')
  const budget = Number(arg('budget', String(DEFAULT_BUDGET)))
  const recipes = only ? RECIPES.filter((r) => r.name === only) : RECIPES
  if (recipes.length === 0) throw new Error(`--only ${only}: no such fixture (${FIXTURE_NAMES.join(', ')})`)

  console.log('')
  console.log(`E2E FIXTURES – schema v${SAVE_SCHEMA_VERSION}, ${recipes.length} to build, budget ${budget} seeds each`)
  console.log('')

  mkdirSync(FIXTURE_DIR, { recursive: true })
  // A partial run keeps the fixtures it is not rebuilding, so `--only pro` cannot silently drop the
  // other four out of the manifest.
  const kept = only && readdirSync(FIXTURE_DIR).includes('manifest.json') ? loadManifest().fixtures : []
  const entries: FixtureEntry[] = kept.filter((e) => !recipes.some((r) => r.name === e.name))

  for (const recipe of recipes) {
    const at = Date.now()
    process.stdout.write(`  ${recipe.name.padEnd(7)} `)
    console.log('searching…')
    const { entry, bytes } = await generate(recipe, budget)
    writeFileSync(`${FIXTURE_DIR}${entry.file}`, bytes)
    entries.push(entry)
    const f = entry.facts
    console.log(
      `    -> ${entry.seed} · week ${f.week} · age ${f.ageYears} · ${money(f.fundsCents)} · rank ${f.kidRank} · ` +
        `${(bytes.byteLength / 1024).toFixed(1)} KiB · ${entry.seedsTried} seed(s) · ${((Date.now() - at) / 1000).toFixed(0)}s`,
    )
  }

  entries.sort((a, b) => FIXTURE_NAMES.indexOf(a.name) - FIXTURE_NAMES.indexOf(b.name))
  const manifest: FixtureManifest = {
    generatedBy: 'tools/e2e-fixtures.ts',
    command: 'npm run e2e:fixtures',
    schemaVersion: SAVE_SCHEMA_VERSION,
    fixtures: entries,
  }
  writeFileSync(MANIFEST_FILE, `${JSON.stringify(manifest, null, 2)}\n`)

  const total = entries.reduce((sum, e) => sum + e.bytes, 0)
  console.log('')
  console.log(`  manifest: ${entries.length} fixtures, ${(total / 1024).toFixed(1)} KiB on disk`)
  console.log('')
  // A sanity line rather than a decoration: the starting funds are a per-background constant, so a
  // week-0 fixture that does not hold it means the recipe wandered off its own preset.
  const fresh = entries.find((e) => e.name === 'fresh')
  if (fresh && fresh.facts.fundsCents !== STARTING_FUNDS_CENTS[fresh.background]) {
    throw new Error('fresh: week-0 funds are not the background\'s starting funds')
  }
}

// THE SAME GUARD THE BENCHES CARRY, AND FOR THE SAME MEASURED REASON (see the long note at the foot
// of tools/econ-bench.ts): this runner's `vite-node` STRIPS THE ENTRY FILE from `process.argv`, so a
// naive `argv[1]` check is false on every invocation and the tool exits 0 having done nothing. npm
// still puts the whole script body in `npm_lifecycle_script`, so the name is looked for in both
// places; `TB_FIXTURES_RUN=1` is the override for a bare `npx vite-node tools/e2e-fixtures.ts`.
// The VITEST arm is what keeps the rot alarm's import from launching a multi-minute seed search.
const NAMED_ON_THE_COMMAND_LINE =
  process.argv.some((a) => a.includes('e2e-fixtures')) ||
  (process.env.npm_lifecycle_script ?? '').includes('e2e-fixtures') ||
  process.env.TB_FIXTURES_RUN === '1'
if (!process.env.VITEST && NAMED_ON_THE_COMMAND_LINE) void main()
