// ⭐⭐⭐ ROUND 44 – THE ONE-OFF THAT WROTE `src/engine/world/smallTalkCorpus.ts`.
//
//     npx vite-node tools/small-talk-corpus-emit.ts            # print to stdout
//     npx vite-node tools/small-talk-corpus-emit.ts --write    # write the module
//
// ⚠⚠ IT IS A ONE-OFF AND NOT A BUILD STEP, which is the round's own ruling: «its output is committed
// as ordinary source – no build step, no codegen in the pipeline, boring TypeScript intact». Nothing
// in `npm run check`, `npm run build` or the dev server runs this file. What keeps the committed
// module honest is `tests/round44-corpus-roundtrip.test.ts`, which re-parses the document on every
// run and compares it to the committed catalogue STRING FOR STRING – so a hand-edit of the generated
// file goes red, and so does a document edit that was never re-emitted.
//
// ⚠ RE-RUNNING IT IS THE ONLY LEGITIMATE WAY TO CHANGE THE 43. If the owner edits a line in
// `docs/specs/small-talk-corpus-2026-09.md`, run this with `--write` and commit the result; do not
// touch the generated module by hand.

import { writeFileSync } from 'node:fs'
import { readCorpus, corpusCounts, CORPUS_STANCES, CORPUS_VOICES } from './small-talk-corpus-parse'
import type { CorpusRow } from './small-talk-corpus-parse'

const OUT = new URL('../src/engine/world/smallTalkCorpus.ts', import.meta.url)

/** ⚠ SINGLE-QUOTED, AND THE ESCAPES ARE THE ONLY TWO THAT MATTER: the backslash first (or it would
 *  escape the escapes that follow it) and the quote. Every one of the 817 payloads carries `"`
 *  characters and many carry apostrophes, which is precisely why this is emitted and not typed. */
function q(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

function emitRow(row: CorpusRow): string[] {
  const out: string[] = []
  out.push(`  // ${row.ref} · ${row.id}`)
  out.push('  {')
  out.push(`    id: ${q(row.id)},`)
  out.push(`    subject: ${q(row.subject)},`)
  out.push(`    stages: [${row.stages.map(q).join(', ')}],`)
  out.push(`    fact: ${row.fact === null ? 'null' : q(row.fact)},`)
  out.push('    voices: {')
  for (const voice of CORPUS_VOICES) {
    out.push(`      ${voice}: {`)
    out.push(`        opener: ${q(row.openers[voice])},`)
    // ⭐ THE `story` SECOND BEAT, on the one row that has one. `SmallTalkVoiceEntry.shared` is
    // OPTIONAL and its absence is what tells the assembler «this situation is one paragraph per
    // route», so an omitted key and an empty string are not the same thing – the key is omitted.
    if (row.shared !== null) out.push(`        shared: ${q(row.shared[voice])},`)
    out.push('        branches: {')
    for (const stance of CORPUS_STANCES) {
      const block = row.stances.find((b) => b.stance === stance)
      if (block === undefined) throw new Error(`${row.ref} has no ${stance} block`)
      out.push(`          ${stance}: {`)
      out.push(`            label: ${q(block.label)},`)
      out.push(`            said: ${q(block.replies[voice])},`)
      out.push('          },')
    }
    out.push('        },')
    out.push('      },')
  }
  out.push('    },')
  out.push('  },')
  return out
}

export function emit(): string {
  const rows = readCorpus()
  const counts = corpusCounts(rows)
  const head = `// ⭐⭐⭐ THE SMALL-TALK CORPUS – **GENERATED FROM \`docs/specs/small-talk-corpus-2026-09.md\`,
// NEVER RETYPED.** ${counts.rows} situations × ${CORPUS_VOICES.length} voices: ${counts.openers} openers, ${counts.labels} stance labels, ${counts.replies} replies, ${counts.shared} shared second beats.
//
// ⭐⭐ THIS IS THE WHOLE CATALOGUE AND NOT A SECOND HALF OF ONE. \`SMALL_TALK_SHIPPED\` – the eight
// situations hand-written in \`lifeBeat.ts\` since wave 2 – was deleted in round 44 and those eight are
// rows \`R45\`-\`R52\` of the same document, brought up to four voices each. \`SMALL_TALK_SITUATIONS\` is
// this array, so «fixed in the code, the document drifted» has no shape left to take.
// ⚠ THE EIGHT ARE FIRST, and the order is a live career's draw rather than a preference: the
// situation is picked with \`pickInt\` over the filtered pool, which reads position.
//
// ⚠⚠ DO NOT EDIT THIS FILE BY HAND. It is written by \`tools/small-talk-corpus-emit.ts\` and pinned,
// string for string, against the document by \`tests/round44-corpus-roundtrip.test.ts\`. A hand-edit
// here goes red; so does a document edit that was never re-emitted. To change a line, change the
// DOCUMENT – the owner's copy lives there (invariant 4) – then re-run the emitter with \`--write\`.
//
// ⚠ IT IS ORDINARY COMMITTED SOURCE AND NOT A BUILD STEP (the round's own ruling). Nothing in
// \`npm run check\`, \`npm run build\` or the dev server generates it; the emitter is a one-off.
//
// ⭐ WHY GENERATION RATHER THAN TRANSCRIPTION: ${counts.openers + counts.labels + counts.replies} authored strings. An agent retyping them
// produces typos that no test can catch, because a test written by the same agent compares against
// what was typed. The document is the source of truth; this file is its projection.
//
// ⚠ \`R3\`'s KEY IS NORMALISED AT THE DOOR – the document writes \`the-stranger's-sock\` and a situation
// id is PERSISTED into \`lifeLog\` as half of the row's \`detail\`, so the apostrophe is stripped by
// \`corpusId\` in the parser rather than here. Ids are append-only: see \`SmallTalkSituation.id\`.
//
// size-budget: generated corpus. Thousands of lines of authored strings with ONE reason to change,
// and the reason is the document. \`scripts/context-audit.mjs\`' 1,000-line trigger is aimed at
// a source file growing past the point where a reader can hold it; this file is not read, it is
// diffed against \`tests/round44-corpus-roundtrip.test.ts\`, and splitting it would buy nothing but two
// files to re-emit. The waiver is acknowledged rather than silent.
//
// ⚠ EVERY ROW IS A **DRAFT** UNTIL HE HAS READ IT. The document says so at its head, and the round
// ledger repeats it: «the 516 replies and 172 openers are drafts he has not read».

import type { SmallTalkSituation } from './lifeBeat'

export const SMALL_TALK_CORPUS: readonly SmallTalkSituation[] = [
`
  const body = rows.flatMap(emitRow).join('\n')
  return head + body + '\n]\n'
}

const text = emit()
if (process.argv.includes('--write')) {
  writeFileSync(OUT, text)
  const counts = corpusCounts(readCorpus())
  console.log(`wrote ${OUT.pathname}: ${counts.rows} rows, ${counts.openers} openers, ${counts.labels} labels, ${counts.replies} replies, ${counts.shared} shared`)
} else {
  console.log(text)
}
