// THE GRACEFUL-ABSENCE LEDGER – L4-1 (10.10). One list, two readers.
//
// The stylesheet DECLARES two Cyrillic subset faces (`src/style.css`, the L4-1 block) whose files are generated by the commands in
// docs/specs/ru-typography-2026-09.md §T3 and are not in the repository yet. Until they land, a declared face with no file is the
// SHIPPED state, not a defect: a Russian session asks, gets a 404 and falls through the family stack to the system face.
//
// Every guard that asks «does each declared font file exist» reads THIS list for its exceptions, and
// tests/i18n-l4-1-fonts.test.ts makes the list shrink: an entry whose file has landed fails there until it is deleted here. So the
// exception can never outlive the absence it documents, and no guard has a private copy of it to forget.
//
// The day the files land: delete both entries, name both files in public/fonts/README.md (tests/legal-assets.test.ts insists), run
// `npm run fonts:probe -- --require-cyrillic <files>` and `npm run check`.
export const GRACEFUL_ABSENT_FONTS: readonly string[] = ['/fonts/manrope-cyr.woff2', '/fonts/caveat-cyr.woff2']
