// ⭐ L3-5 (10.10) – THE LIFE BEATS' CLASS-(b) `cp` KEYS, generated by the net's own scan and committed so a NEW key is a decision (tests/i18n-l3-5-life-beats.test.ts §1 proves this list is exactly
// what the life files spell that no old save can hold: no more, no fewer; to regenerate after a deliberate change run `L35_WRITE_KEYS=1 npx vitest run --project unit tests/i18n-l3-5-life-beats.test.ts`).
// They are the sentences a life-beat PROMPT composes at snapshot time – the announcement's nine "how long they have been together" sentences (one per shape of the span, a counted form being a whole
// sentence per form) and the `{0} {1}` join that sets a sentence after another (small talk's frame before its opener, the pool line before the span) – NEVER stored, so no old save can hold one and the
// frozen v92 table has no entry for them (the L3-3 briefing's and the L3-4 diary's are the precedent; i18n-l3-1-ledger-writers.test.ts spreads this list into its NEW_KEYS). The two milestone
// sentences the wave also spells as `cp` (the divorce, the wedding day) ARE the table's own keys and are not here.
export const LIFE_CLASS_B_KEYS: readonly string[] = [
  "They have been together for 1 month.",
  "They have been together for 1 year and 1 month.",
  "They have been together for 1 year and {0} months.",
  "They have been together for 1 year.",
  "They have been together for less than a month.",
  "They have been together for {0} months.",
  "They have been together for {0} years and 1 month.",
  "They have been together for {0} years and {1} months.",
  "They have been together for {0} years.",
  "{0} {1}",
]
